### ISSUE TITLE
Home Page | Fix bugs

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#116]
## SUMMARY
When a user is auth, we show `/home` where they can find quick access to `Upcoming Bookings`, `Wishlist`, `Past Tours` & `Tours Awaiting Rating`. Now that we have created all those pages, we need to make sure the links work properly as currently are 404s.

In addition, if user is brand new and doesn't have any items on those sections, we should show the `Search Hero Banner` from `Landing Page` on top area. Right now, it's showing `Spotlight Destinations` without the `Search Hero Banner`

### ACS

- [ ] Link the CTAs under each section of `/home` with the proper section on `Traveler Account`
- [ ] Create initial state with params for the tab system
- [ ] Show `Search Hero Banner` when user doesn't have any items in the sections for `Home`

**Comment by kateinvan** [comment]
@AhmadForhat Hi Admad, I see the same `search hero banner` with both login info now.

**Comment by sebas-led** [comment]
@kateinvan Try again with Naoki's credential. I can see the upcoming bookings now showing instead of the Search Hero Banner.
LGTM

**Comment by kateinvan** [comment]
oh now I can see the upcoming booking. thanks Seba :)
there's a small white gab between the top blue bar and the hero section. other than that, LGTM!
<img width="461" alt="Screenshot 2023-11-14 at 11 43 50 AM" src="https://github.com/toursbylocals/wiki/assets/113576283/d3a8116b-8923-4f4e-bfd3-5ac3e0270231">

**Comment by AhmadForhat** [comment]
@kateinvan, we should create a different ticket to fix the navbar problem. Same pr changed the navbar breakpoint and that caused the issue. It would be better to study this before making any changes. BTW I think Miya was fixing that

**Comment by sebas-led** [comment]
@kateinvan @AhmadForhat Added on the ticket https://github.com/toursbylocals/wiki/issues/150
