### ISSUE TITLE
Login for Admin App

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#147]
## SUMMARY
ToursByLocals Staff have accounts that are not on the marketplace or Kitchen, and therefor, we need to create login page for Admin users. 

### ACS

- [ ] Create login for Admin App users following our current login design for Kitchen (removing the radio button)
- [ ] Make sure the User that loggs in can only see the Admin App Modules they have the rights for

### RESOURCES
[Figma Link](https://www.figma.com/proto/05Lni9rdCbn4jzXrvnaYPe/Kitchen?page-id=6716%3A294013&type=design&node-id=6716-301199&viewport=486%2C445%2C0.25&t=P8M6SLJEFK7IA2oB-1&scaling=min-zoom&starting-point-node-id=6716%3A301199&show-proto-sidebar=1)

**Comment by AhmadForhat** [comment]
@laskokonopa @kateinvan @Mica-pfl @sebas-led @ecurtosi99 

Please test the login when you have time

https://tblv3-kitchen-staging-c94ff87374cd.herokuapp.com/login

**Comment by ecurtosi99** [comment]
LGTM

**Comment by sebas-led** [comment]
LGTM
@AhmadForhat Out of scope, but I'm wondering if we should remove 'forgot password' from Admin Login for security reasons...What are your thoughts?

**Comment by kateinvan** [comment]
@sebas-led can we change the title `Log in` to `Admin Log In`, or change the right side of the photo? users might be confused about whether it's for marketplace or admin.

**Comment by Mica-pfl** [comment]
I would suggest partner log in in that case. LGTM

**Comment by Mica-pfl** [comment]
LGTM

**Comment by sebas-led** [comment]
Created a new ticket for changing wording and forgot password, as it was out of scope on this ticket
