### ISSUE TITLE
Blog | Final Changes

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#148]
## SUMMARY
We recently closed the `Blog` and some enhancements are required to have it ready for prod.

- Recent blogs should be last 12 months 
- See archived posts only show last 3 months but should show every month and year with a post after month 12
- On Post, remove the day of the post (ie: Wed or Thu). Show only Mon DD YYYY
- Apply Meta Tags on Blog Post according to the [DOCUMENTATION](https://docs.google.com/document/d/130FTwYe7dF6WqKX6RZRf_eJd8FBxIgJEMiygbzX052I/edit#heading=h.zedqcfesfy71)

### ACS

- [x] Implement the changes listed above

### VISUALS
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTNHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--41eb36fe5413eda14d3021fef3ef3549e878a2da/Screenshot%202023-11-10%20at%2017.41.21.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMS9HQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81c5d0fc2f53d0a07313c192605dcbcbbae896b3/Screenshot%202023-11-10%20at%2017.41.54.png)

**Comment by growebux** [comment]
QA link for testing: http://localhost:3000/travel-blog

**Comment by sebas-led** [comment]
@growebux What's missing to move this one to QA? :)

**Comment by growebux** [comment]
@sebas-led Moving it now

**Comment by growebux** [comment]
@sebas-led I had to rename one field and I created a PR for it:

https://github.com/toursbylocals/tblv3-api/pull/850

as soon it gets merged I will move this ticket to review.

**Comment by growebux** [comment]
@laskokonopa @kateinvan @sebas-led 

Could you validate?

https://tblv3-staging.herokuapp.com/travel-blog

**Comment by kateinvan** [comment]
LGTM it works really well :)

**Comment by Mica-pfl** [comment]
LGTM

**Comment by sebas-led** [comment]
LGTM
