### ISSUE TITLE
Guide Account | Settings | Personal Information

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#152]
## SUMMARY
Within the `Kitchen`, we have a section called `Personal Information` where the Guides can input all the individual information, the payout details and KYC to Adyen, if needed. Overall, the section contains:
- First Name
- Last Name
- Email Address (disabled input)
- Address (use address component, no need for autocomplete)
- Home Phone (optional)
- Mobile Phone
- Emergency Contact
   - First Name
   - Last Name
   - Phone Number (design has email but should be phone number)
- Payout details (separate ticket)

### ACS

- [x] Create the page following the design on `Figma`
- [x] All fields are mandatory except Home Phone
- [x] Re-use the same fields from `Personal Information - Customer Account`
- [x] Create initial state for payout method using the `alert` component from `DSTBL`
- [x] If there is a payout method selected, show Registered as, Organization name (if applicable), Payout method (PayPal, Direct deposit or Wire transfer) and Preferred currency with option to Add/Edit

### VISUALS
<img width="1061" alt="Screenshot 2023-12-06 at 09 42 42" src="https://github.com/toursbylocals/wiki/assets/107880609/8e552bb0-559d-411b-8e4b-af856b31e7dd">

Payout Method - Initial State
<img width="1063" alt="Screenshot 2023-12-06 at 09 43 05" src="https://github.com/toursbylocals/wiki/assets/107880609/b5232c49-2874-44bb-afdb-9b4b69c15c84">

Payout Method - Inidividual
<img width="1067" alt="Screenshot 2023-12-06 at 09 43 39" src="https://github.com/toursbylocals/wiki/assets/107880609/568acc92-2858-4e5d-8b75-b044e46c8662">

Payout method - Organization
<img width="1064" alt="Screenshot 2023-12-06 at 09 43 56" src="https://github.com/toursbylocals/wiki/assets/107880609/b0722fe7-ab76-4033-a42f-4471b3483d78">

### RESOURCES
[Figma Link to Personal Information](https://www.figma.com/file/05Lni9rdCbn4jzXrvnaYPe/Kitchen?type=design&node-id=456-50328&mode=design&t=hz4TbF6NrWmnBrsp-0)
[Figma Link to Prototype](https://www.figma.com/proto/05Lni9rdCbn4jzXrvnaYPe/Kitchen?page-id=456%3A50328&type=design&node-id=3331-65959&t=hz4TbF6NrWmnBrsp-0&scaling=contain&starting-point-node-id=3331%3A65959&show-proto-sidebar=1)

**Comment by sebas-led** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RD-team-61a6bf56a3b924001cb03cba/issues/toursbylocals/wiki/152?planning-poker) with Zenhub @AhmadForhat @growebux @miyabitanimchi @YumiKimbara

**Comment by nk18chi** [comment]
@sebas-led @Mica-pfl There are many shared components in the following ticket(https://github.com/toursbylocals/kitchen/pull/124), so this ticket will be on hold until the other ticket has passed in QA.

**Comment by YumiKimbara** [comment]
@kateinvan @sebas-led @laskokonopa @ecurtosi99 @Mica-pfl
Can you check the URL below when you have time? It is connected to API, so you can save data on DB.

https://tblv3-kitchen-staging-c94ff87374cd.herokuapp.com/guide/settings

[ykimbara@toursbylocals.com](mailto:ykimbara@toursbylocals.com)
Cupcake1234!

**Comment by sebas-led** [comment]
LGTM

**Comment by kateinvan** [comment]
LGTM

**Comment by laskokonopa** [comment]
LGTM

**Comment by ecurtosi99** [comment]
LGTM
