### ISSUE TITLE
Guide & Travel Agent (Admin) Accounts | Payments Module | Tab System

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#154]
## SUMMARY
Both, Guides and Agents (Admins only) have the ability to see their balance, withdraw the funds and see all the payout history.

This ticket is to create the tab system with the following options:
- Balance
- Payment History

Note: Payments section for Travel Agents is virtually identical to guide account except for the side nav.

### ACS

- [ ] Create the tab system for `Payments` with options Balance and Payment History
- [ ] Highlight the tab selected

### VISUALS
**Desktop**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelRMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d811e2cb482ddbfce30b32352177b00fdb2632c/Screenshot%202023-11-13%20at%2012.11.54.png)
**Tablet**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemJMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ef5e77484393df309a376d79fa13c74e61f130d/Screenshot%202023-11-13%20at%2012.12.17.png)
**Mobile**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemZMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd1992429d56c9d00cb11d955a369fdd379f7b86/Screenshot%202023-11-13%20at%2012.12.33.png)

### RESOURCES
[Figma Link to Payments](https://www.figma.com/file/05Lni9rdCbn4jzXrvnaYPe/Kitchen?type=design&node-id=1730-124384&mode=design&t=8Dn4GXRZpQG49pXj-0)

[Figma Link to Prototype](https://www.figma.com/proto/05Lni9rdCbn4jzXrvnaYPe/Kitchen?page-id=1730%3A124384&type=design&node-id=2042-51685&t=8Dn4GXRZpQG49pXj-0&scaling=scale-down&starting-point-node-id=2042%3A51685&show-proto-sidebar=1)

**Comment by sebas-led** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RD-team-61a6bf56a3b924001cb03cba/issues/toursbylocals/wiki/154?planning-poker) with Zenhub @AhmadForhat @growebux @miyabitanimchi @YumiKimbara

**Comment by YumiKimbara** [comment]
@kateinvan @sebas-led @laskokonopa @ecurtosi99 @Mica-pfl
Could you check them at your convenience?
Now my user info is admin for both guide and agent accounts, so you can access to both payment information. If it is a non-admin user, I hide the section payments from the side nav bar as I confirmed with Seba.

https://tblv3-kitchen-staging-c94ff87374cd.herokuapp.com/agent/payments
https://tblv3-kitchen-staging-c94ff87374cd.herokuapp.com/guide/payments

[ykimbara@toursbylocals.com](mailto:ykimbara@toursbylocals.com)
Cupcake1234!

**Comment by sebas-led** [comment]
@YumiKimbara 
- Sub-heading should be Payments while it currently shows Booking History. 
- On Guide Account, Payments is missing on the sidebar. Could you add it, exactly the same as on Travel Agent - Admin?

Guide
<img width="684" alt="Screenshot 2024-01-30 at 08 37 59" src="https://github.com/toursbylocals/wiki/assets/107880609/782ba4bb-d1a2-4bca-bf05-aef2d3898db7">

Agent Admin
<img width="723" alt="Screenshot 2024-01-30 at 08 38 11" src="https://github.com/toursbylocals/wiki/assets/107880609/021eaa10-c8bb-4867-942d-8fd68e96a279">

**Comment by kateinvan** [comment]
same as Seba's comments, other than that LGTM

**Comment by YumiKimbara** [comment]
@sebas-led 

> On Guide Account, Payments is missing on the sidebar. Could you add it, exactly the same as on Travel Agent - Admin?

I checked one more time, but I think you can see the payments on the sidebar when you access to the page as admin guide. Did you make sure that you logout and login as a guide? You need to logout from agent first.

> Sub-heading should be Payments while it currently shows Booking History.

Can I fix this in my current task since it is just fixing text, so I think it is better to fix on my current task rather than creating a new PR.
