### ISSUE TITLE
Guide & Travel Agent (Admin) Accounts | Payments Module | Payment History Section

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#155]
## SUMMARY
Both, Guides and Agents (Admins only) have the ability to see their balance, withdraw the funds and see all the payout history.

This ticket is to create the Payment History Section with the following sections:
- List View with:
   - Payment Date
   - Amount paid in payout currency
   - Payment method
   - Reference ID
   - Actions > If clicked, opens the Payment Details with
      - Payment Date
      - Total amount paid in payout currency
      - Payment Method
      - List view with Transaction Date, Tour Date, Type, Booking References, TBL Invoice ID, Traveler, Amount in payout currency

Note: Payments section for Travel Agents is virtually identical to guide account except for the side nav.

### ACS

- [ ] Create the Payment History Section following the design on `Figma`
- [ ] Items on the list view are for each payout sent to the partner (a single row could have multiple bookings)
   - Payment Method can be Direct Deposit, Wire Transfer or PayPal
- [ ] If user clicks on the actions, opens the details of the transaction
   - Payment Date is the one when the payout took place
   - Transaction Date is the one when the booking was made
   - Tour Date is the one when the tour took place
   - Type is Sale, Elite Bonus or Adjustment
- [ ] Add a new style (white text style) to the Button component and apply this to everypart that using wrong color button

### VISUALS
**Desktop initial state**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOC9MQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3f3abbb54ed26b53e97ac3c54e4ef65ed4e1739/Screenshot%202023-11-13%20at%2013.32.23.png)

**Desktop for Payment Details**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODNMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44195f7f1245aefa94bcecdf2f26a96377c98606/Screenshot%202023-11-13%20at%2013.31.50.png)

**Tablet**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUxMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f194a93c375883eccdc15fdda291886b6ae48759/Screenshot%202023-11-13%20at%2013.32.53.png)

**Mobile**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVBMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2719598be77cc429c1d55ef5faf255162f9d5d4/Screenshot%202023-11-13%20at%2013.33.10.png)

### RESOURCES
[Figma Link to Payments](https://www.figma.com/file/05Lni9rdCbn4jzXrvnaYPe/Kitchen?type=design&node-id=1730-124384&mode=design&t=8Dn4GXRZpQG49pXj-0)

[Figma Link to Prototype](https://www.figma.com/proto/05Lni9rdCbn4jzXrvnaYPe/Kitchen?page-id=1730%3A124384&type=design&node-id=2042-51685&t=8Dn4GXRZpQG49pXj-0&scaling=scale-down&starting-point-node-id=2042%3A51685&show-proto-sidebar=1)

**Comment by sebas-led** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RD-team-61a6bf56a3b924001cb03cba/issues/toursbylocals/wiki/155?planning-poker) with Zenhub @AhmadForhat @growebux @miyabitanimchi @YumiKimbara

**Comment by YumiKimbara** [comment]
@kateinvan @sebas-led @laskokonopa @ecurtosi99 @Mica-pfl
Can you check the URLs below when you have time? This is only a front-end task, so I used mock data.

https://tblv3-kitchen-staging-c94ff87374cd.herokuapp.com/agent/payments
https://tblv3-kitchen-staging-c94ff87374cd.herokuapp.com/guide/payments

[ykimbara@toursbylocals.com](mailto:ykimbara@toursbylocals.com)
Cupcake1234!

**Comment by kateinvan** [comment]
@YumiKimbara hi Yumi, I found some minor issues while reviewing

- could you make 'Total amount paid to you' as the Figma design? on mobile, the line alignment is broken. I attached a reference image below. 
<img width="905" alt="Screenshot 2024-02-08 at 3 50 43 PM" src="https://github.com/toursbylocals/wiki/assets/113576283/240bfc1b-ee49-4153-b9cc-f26a773570a1">

- on the Payment history detail page, we don't need the tab menu
- and I wonder why the back arrow button changed to black. it is supposed to be white.
- and the header height changes when it has the back arrow button. not sure this scope is under this ticket.
https://github.com/toursbylocals/wiki/assets/113576283/8071bcf1-41eb-422c-8346-315ee66de589

**Comment by sebas-led** [comment]
@YumiKimbara Besides of Kate's comment, when changing the pagination, it goes from 1/2 to 3/2 instead of 2/2. Could you check?

**Comment by YumiKimbara** [comment]
Sorry for my late reply and thank you so much for checking!!

@kateinvan 
>and I wonder why the back arrow button changed to black. it is supposed to be white.

It seems like we don't have a white color text button in the design system right now, and I think it is better not to manually change the text color since I talked about this with other developers. right now, this button is `variant="secondary"` and `type="text"`. What do you think? I think the solution is either find different button design from the current design system or create a new variant for white text colour I guess, but please let me know your opinion :)

@sebas-led
Sorry, I always forget to mention, but pagination will be done when I work on backend :)

**Comment by YumiKimbara** [comment]
@kateinvan 
Sorry one more thing!

>and the header height changes when it has the back arrow button. not sure this scope is under this ticket.

Seems like the header has padding and the button has a height 32px, so because of those two reasons, whenever there is a button, the header height changes.  Both header and button comes from design system, so I need to modify that. It is not a big deal to change that, but just want to double check if it is important to fix this. In my opinion, I agree with you, and it is weird that the height has changes, so I think it is okay to fix the design system! If I need to fix this, can I ask header height just in case? (maybe 61px?)

**Comment by kateinvan** [comment]
@YumiKimbara 

- The header height in Figma is 68 px 
- the white icon button: so currently, it's a text button? I think the text button also doesn't make sense haha I think we need to add an icon type under the button component unless we fix it manually. @laskokonopa what do you think?

**Comment by laskokonopa** [comment]
@kateinvan @YumiKimbara Since we use this everywhere we prob should update the component.

**Comment by YumiKimbara** [comment]
@laskokonopa @kateinvan Thank you for your opinions! I will check the Button component to see which way to add a new style to the component or set the arrow to white in the default state is better to implement and make sure to change that!

@sebas-led 
I am gonna add a new ACS to this ticket which is adding a new style to the Button component, and make sure to change the everything using wrong color arrows. I am sure this ACS doesn't take a lot of time to finish, so I am just gonna do this in this ticket!

**Comment by growebux** [comment]
@YumiKimbara When implementing the enhancement, please be careful not to change the states (width, height, shape) of existing buttons. Instead, please add what is missing as changing the states can affect all the buttons in the entire application and may cause multiple bugs. Please ensure that you add a new variation without changing the states.

@sebas-led @kateinvan @laskokonopa

**Comment by YumiKimbara** [comment]
@growebux Sounds good! I will add the new variant for that!

**Comment by growebux** [comment]
> @kateinvan @YumiKimbara Since we use this everywhere we prob should update the component. Or can the arrow be set to white in default state in this case.

This button is liked with the source and it's being used by all the apps we are creating, making the change you said will break the design of every layout where you used the button in that state, please instead a new set variation with all the states for a new button...


@laskokonopa @kateinvan

**Comment by laskokonopa** [comment]
@growebux @kateinvan @sebas-led @YumiKimbara Thanks Rafa, we will add this new variant to the buttons with the states. I will run it by you as well after.

**Comment by YumiKimbara** [comment]
@kateinvan @sebas-led @laskokonopa @ecurtosi99 @Mica-pfl
I fixed the code based on the QA comments below.

- could you make 'Total amount paid to you' as the Figma design? on mobile, the line alignment is broken. I attached a reference image below.
- on the Payment history detail page, we don't need the tab menu

Other QA comments will be fixed in a separate ticket.

https://tblv3-kitchen-staging-c94ff87374cd.herokuapp.com/agent/payments
https://tblv3-kitchen-staging-c94ff87374cd.herokuapp.com/guide/payments

[ykimbara@toursbylocals.com](mailto:ykimbara@toursbylocals.com)
Cupcake1234!

**Comment by Mica-pfl** [comment]
Thank you Yumi! LGTM, pagination issue Sebas mentioned is still there though

**Comment by YumiKimbara** [comment]
@Mica-pfl Thank you for checking! I need to connect API to manage pagination, so I will fix that once I grab the backend ticket for this!

**Comment by kateinvan** [comment]
LGTM thanks Yumi :)

**Comment by sebas-led** [comment]
LGTM
Thanks @YumiKimbara
