### ISSUE TITLE
Help Page | Changes after Internal Validation

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#158]
## SUMMARY
We created an internal validation for the `Help Page` and noticed some enhancements that would be helpful.

- It is not clear for users about the ‘00 more’ in the FAQ area to check the total number of articles. However the number of articles is not important for users, so my suggestion is to change the '00 more' to ‘See more’.
- Text with hyperlinks are hard to distinguished

### ACS

- [x] Replace 'XX more' by 'See more'
- [x] Make each Question in the box clickable
- [x] Change font colour when a text is hyperlinked (same as what it was implemented on the `Blog`). Check if we need to sanitize the css first

### VISUALS
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVlzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4056a58decb81fb43d9328e657402f298d97d6e0/Screenshot%202023-12-04%20at%2010.11.46.png" alt="Screenshot 2023-12-04 at 10.11.46.png" />

![Screenshot 2023-12-04 at 9 12 10 AM](https://github.com/toursbylocals/wiki/assets/107880609/04548b73-7b86-4b6d-9117-00bfced0e951)

**Comment by growebux** [comment]
Link: https://tblv3-staging.herokuapp.com/

**Comment by kateinvan** [comment]
@growebux it works well and looks good! (but it takes me to the current v2 platform) thanks Rafa :)

**Comment by growebux** [comment]
> @growebux it works well and looks good! (but it takes me to the current v2 platform) thanks Rafa :)

Yeah, we need to change it from the db because there is a link to v2.

**Comment by sebas-led** [comment]
LGTM, thanks Rafa for the hard word !
@kateinvan Ops will change the FAQ content before we release v3 so that it doesn't happened

**Comment by sebas-led** [comment]
@ecurtosi99 @Mica-pfl Could you review?

**Comment by ecurtosi99** [comment]
LGTM
