### ISSUE TITLE
Migrate Rest of Design Docs for MTJ - Wiki

### ISSUE THREAD

**Issue by codedavinci** [toursbylocals/wiki#16]
- [x] Migrate the rest of the UX docs 

- [x] PS: List in the comments all the documents that have been added to the wiki

**Comment by growebux** [comment]
The following documents have been added to the Wiki Documentation:

- MTJ - Business Rules - Add New Memory
- MTJ - Business Rules - Explore page (Auth & Non-Auth)
- MTJ - Business Rules - Feed page (Auth only)
- MTJ - Business Rules - Memories
- MTJ - Business Rules - Nav Bar (Auth & Non-Auth)
- MTJ - Business Rules - Non-Authenticated User
- MTJ - Business Rules - View_Edit Memory
- Developer Success Algorithm

We don't have any other documentation to add right now. Our team is creating a few new documentation and will be added to the Wiki in the following days.
