### ISSUE TITLE
Messaging System | Create flow for starting a Chatroom

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#161]
## SUMMARY
We have created the `Messaging System` ecosystem and now need to connect it to the flow for how users would start a new chatroom from the `Marketplace`. There are 4 ways a message could be started:
- Guide Profile
- GuideCard
- Tour Details
- Booking Confirmation

Depending on where the message is generated, the first message would contain a default subject that is added to the first bubble in the chatroom. The UI can be followed on https://github.com/toursbylocals/dstbl/issues/969

### ACS
- [x] When user clicks on `Message Guide`, redirect to the `Messaging System` in a new chatroom
- [x] Show a popover with fields Tour Date (optional), Party Size (optional) and Message (mandatory)
- [x] Once message is sent, the first bubble would show the information from the popover and where the message was generated. In case of Guide Profile or Guide Card, show 'General Inquiry'. In case of Tour Details, show 'Inquiry about Tour #34123 - Best tour of London' (Tour ID and Tour Title)

### VISUALS
**Popover to add details**
<img width="1431" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1ZZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0df5f77fb6989d243d82aaf67133c8f839399745/Screenshot%202023-12-13%20at%2008.56.15.png" alt="Screenshot 2023-12-13 at 08.56.15.png" />

**First bubble showing message source and details**
<img width="1412" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2RZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--336c7f9afc0c24aab7ce9504c22c156e37b138fc/Screenshot%202023-12-13%20at%2008.56.39.png" alt="Screenshot 2023-12-13 at 08.56.39.png" />

### RESOURCES
[Figma Prototype](https://www.figma.com/proto/0foDnrR5AX93zzXI0t4eMR/V3_NEW?page-id=16802%3A78779&type=design&node-id=16802-79000&viewport=-1217%2C348%2C0.23&t=2GGFBjs4FIVFJjWx-1&scaling=scale-down&starting-point-node-id=16842%3A62539&show-proto-sidebar=1)

**Comment by AhmadForhat** [comment]
@laskokonopa @kateinvan @sebas-led @Mica-pfl @ecurtosi99 

Hi, please test this ticket when you have time

Don't forgot to login to be able to see the message system functions

ahmad-traveller@test.ca
Ahmad123!

https://tblv3-staging.herokuapp.com/
https://tblv3-staging.herokuapp.com/customer/messages

**Comment by sebas-led** [comment]
@Trs-24 Due to issues on the staging env as of now, I can't do the full flow of starting a message from guide profile, guide card and tour details page to complete the QA. However, with the QA credentials, I was able to test the messaging system interface and this are the findings: 
- When attaching an image, it's not possible to click on it to open the file, which would make images very small. It does work for pdf documents tho. Could you check?
- The calendar icon is showing always and clicking on it doesn't lead anywhere. The icon should display only if there is an upcoming booking between users and clicking on it should redirect to the `booking confirmation` in a new tab. Could you check?

**Comment by kateinvan** [comment]
@Trs-24 I also can't review the whole flow, but I checked the popup.

- could you use the same data picker on the Tour Detail page? The current one looks a bit different
- could you make date and party size field in two lines like Figma design on mobile view? currently, the data picker is cut off. 
<img width="406" alt="Screenshot 2024-02-08 at 11 28 18 AM" src="https://github.com/toursbylocals/wiki/assets/113576283/2aaa8a6f-ed45-42c5-9e10-5bc8800a6726">

- and could you change the default subject text to 16px, 500 weight?

**Comment by sebas-led** [comment]
@Trs-24 Was able to validate the different flows and they work as expected, thanks for that ! Remaining points on the other comments

**Comment by sebas-led** [comment]
Created new ticket for tackling all QA comments from validations under https://github.com/toursbylocals/wiki/issues/182
