### ISSUE TITLE
Help | Create Travel Agent variation

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#168]
## SUMMARY
We have created the `Help` page for the `Marketplace` for non-auth users. The auth users have also a Help page with some minor modifications as per the UI (https://github.com/toursbylocals/dstbl/issues/965):
- Auth Traveler > Same as non-auth but with option to Contact Support (it opens a new ticket and redirects user to Messaging System)
- Auth Guide > Same as auth Traveler but FAQs are applicable to Squad=Guide and with option to Contact Support (it opens a new ticket and redirects user to Messaging System)
- Auth Travel Agent > Same as auth Traveler but FAQs are applicable to Squad=Agent and with option to Contact Support (it opens a new ticket and redirects user to Messaging System)
- Same as auth Traveler but FAQs are applicable to Squad=Applicant and with option to Contact Support (it opens a new ticket and redirects user to Messaging System)

This ticket is to create the Help Page for Travel Agents and the modal to start the contact us. Anything after submitting the contact on the modal is out of scope in this ticket.

### ACS

- [x] Create a variation of Help page based on the auth user type for Travel Agents
- [x] Create `Contact Support` modal
- [x] The Reasons and Categories shown are correlated
   - Categories on the documentation correlates to Reason for contact on modal
   - Reasons on the documentation correlates to Subject for contact on modal

### VISUALS
**Layout**
<img width="1034" alt="Screenshot 2023-12-28 at 16 26 22" src="https://github.com/toursbylocals/wiki/assets/107880609/95099854-d110-4363-bd58-f6694f755ed5">

**Contact Support Modal**
<img width="1037" alt="Screenshot 2023-12-28 at 16 26 39" src="https://github.com/toursbylocals/wiki/assets/107880609/8c30f9b3-48e8-4539-9bed-6edd3298e34a">

### REFERENCES
[Figma](https://www.figma.com/file/0foDnrR5AX93zzXI0t4eMR/V3_NEW?type=design&node-id=16802-78779&mode=design&t=GRiFoTeXFsXvJt5v-0)
[Prototype](https://www.figma.com/proto/0foDnrR5AX93zzXI0t4eMR/V3_NEW?page-id=16802%3A78779&type=design&node-id=16876-128936&viewport=-2823%2C148%2C0.16&t=Y26jobNEdcHQW5iP-1&scaling=scale-down&starting-point-node-id=16876%3A128936)
[Reason and Categories for Travel Agents > v3 tab > Trigger column = help/travel-agent](https://docs.google.com/spreadsheets/d/1Yk_wBGdwDKGS2_vW9GA9NLMsqJfEzuZHa8iFmJHxsyE/edit#gid=0)

**Comment by AhmadForhat** [comment]
@sebas-led @Mica-pfl we didn't implement yet the message system can we just redirect the user and create another ticket to implement that after we finish the message system

**Comment by AhmadForhat** [comment]
@sebas-led @Mica-pfl we don't have the options for subjects and reasons... can you provide that just to double-check if is everything fine

**Comment by sebas-led** [comment]
@AhmadForhat Sorry for that. This ticket is to create the Help variation and modal for contact us, but the rest would be done later by Taras. I will update the ticket and ACS

**Comment by growebux** [comment]
```
public boolean isGuideArea() { return NumberUtilities.safeIntOf(toFaqtopic().area()) == 1; }
  public boolean isPublicTravelerArea() { return NumberUtilities.safeIntOf(toFaqtopic().area()) == 2; }
  public boolean isAdminArea() { return NumberUtilities.safeIntOf(toFaqtopic().area()) == 3; }
  public boolean isTravelAgentArea() { return NumberUtilities.safeIntOf(toFaqtopic().area()) == 4; }
  public boolean isGuideApplicantArea() { return NumberUtilities.safeIntOf(toFaqtopic().area()) == 5; }
  public boolean isAffiliateArea() { return NumberUtilities.safeIntOf(toFaqtopic().area()) == 6; }
```

**Comment by growebux** [comment]
@sebas-led last acs:

If a user is not logged in, we cannot display FAQs specific to applicants due to the non-existence of a squad. Squads allow differentiation, and their non-existence is indicated by "null" that we use for fallback the FAQs to "Customer" public.

I think the last acs is mixing not possible scenarios.

**Comment by sebas-led** [comment]
@growebux We went over this on Slack, solved :)

**Comment by growebux** [comment]
@laskokonopa @kateinvan @sebas-led 

Can you please log in and review the recent changes made to the FAQ using the appropriate user credentials? 

Please test the contact form and add a category, reference code, and subject to the message. Note the maximum limits for words and characters.

Link: https://tblv3-staging.herokuapp.com/help


Login: {"email.current": "admin-test-agent@test.qa"}
Password: Rafael123!

Login: {"email.current": "user-test-agent@test.qa"}
Password: Rafael123!

Login: {"email.current": "administrator-test-admin@test.qa"}
Password: Rafael123!

Login: {"email.current": "guide-test-user@test.qa"}
Password: Rafael123!

Login: {"email.current": "affiliate-test-user@test.qa"}
Password: Rafael123!

**Comment by growebux** [comment]
I will change the "See more" with "Contact Support" on the header.

**Comment by kateinvan** [comment]
all good but I wanna ask one thing to fix if it's possible.

- I can't see the CTA button until scrolling down on the modal. can you make it visible to increase the height of the modal?
- additionally, can you change the dark background to 60%? currently it's 90%. thanks :)

<img width="414" alt="Screenshot 2024-02-21 at 12 01 32 PM" src="https://github.com/toursbylocals/wiki/assets/113576283/6207049b-c123-4741-b0e1-bdaed58e8cb4">

**Comment by growebux** [comment]
@kateinvan I couldn't reproduce the error on my end using the  https://tblv3 staging.herokuapp.com/help

[ba077a68-8ed8-4388-a9f5-c9d1fa213490.webm](https://github.com/toursbylocals/wiki/assets/70495348/cd3727fa-3f6f-46f0-bb6f-089208093f63)

can we have a call?

**Comment by sebas-led** [comment]
@growebux Thanks for the hard work, it's looking amazing. A few questions:
- If user clicks on a category or question and then tries to click on Contact Support (See more for now) CTA, it doesn't open the modal. Could you check?

https://github.com/toursbylocals/wiki/assets/107880609/bd4073a0-49ca-44c0-8231-62a5b9094605

- Do we have an example of an Applicant too?
- I made a mistake in the documentation, sorry for that. Not all the Category/Reasons in the document are applicable to every squad. Each squad should have specific ones. I just added this into the document. If it's a big change, I can create a separate ticket and I apologize for the mistake 
- Not necessarily part of this ticket, but can we connect the places that would lead to /help?
   - Non auth and Travellers > NavBar
   - Guides and Travel Agents > Kitchen > Sidebar
   - Applicants > Kitchen > Application Process> Sidebar
   - Admin > Sidebar

**Comment by kateinvan** [comment]
sorry Rafa, I decreased the width only. so, LGTM

just add some notes for future improvement:
- make the dark background and open & close action for the modal consistent
- set minimum words or characters to send a message to prevent generating short meesages

**Comment by growebux** [comment]
@sebas-led @kateinvan Thanks for your feedback.

Sebas, I will check the changes you commented on the documentation to measure the effort, right after that I will give you a position if we need to create a new ticket or not.

Sure, I can implement the changes on each app, let me analyze the scope of changes and new requirements.

I will share the Applicant account too after implementing the documentation changes and testing them.

Thanks

**Comment by growebux** [comment]
@sebas-led 

We can add these two on a new ticket, the API change, and the implementation of the /help on different applications.

> I made a mistake in the documentation, sorry for that. Not all the Category/Reasons in the document are applicable to every squad. Each squad should have specific ones. I just added this into the document. If it's a big change, I can create a separate ticket and I apologize for the mistake
> Not necessarily part of this ticket, but can we connect the places that would lead to /help?
> Non auth and Travellers > NavBar
> Guides and Travel Agents > Kitchen > Sidebar
> Applicants > Kitchen > Application Process> Sidebar
> Admin > Sidebar

The rest mentioned I am implementing now.

**Comment by sebas-led** [comment]
@growebux In which PR are you implementing the remaining changes? Just to keep track and be able to check once it's merged :)

**Comment by laskokonopa** [comment]
@growebux Other then what Kate mentioned with the button not showing up and have to scroll LGTM.


<img width="1191" alt="Screenshot 2024-02-23 at 1 02 59 PM" src="https://github.com/toursbylocals/wiki/assets/134641824/d6055aa4-d1b6-412b-8ca3-9ce2ebe428cc">

**Comment by growebux** [comment]
Hey @laskokonopa we need to test the view on the viewport we support by UX > 414x896, 768x1029, 1366x768, 3000x2000 as you can see on the image below:

You can use the extension Responsive Viewer to QA with the settings above.

![image](https://github.com/toursbylocals/wiki/assets/70495348/1acc7d1a-0fcb-4daa-a3a7-059c93817c88)

**Comment by sebas-led** [comment]
LGTM
