### ISSUE TITLE
Error Pages | Enhance the Front end

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#170]
## SUMMARY
We currently have an error page template that is used for different cases. However, it doesn't contain any logo or navigation to go back to the site. The updated design ticket with the UI can be found [HERE](https://github.com/toursbylocals/dstbl/issues/1011)

### ACS

- [x] Enhance the error pages with the new updated design following `FIGMA`
- [x] Use the same design for 500 error pages
- [x] The button to go back to homepage should redirect users depending on the App:
   - [x] Marketplace should redirect to the Landing Page or Home (non auth and auth users)
   - [x] Kitchen should redirect to the Login for non-auth users, Booking Management for Guides and Home for Travel Agents
   - [x] Admin should redirect to the Login

### VISUALS
**Currently**
<img width="1488" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFNOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16f7e210007885b69909f67c44898ab1f8748039/Screenshot%202023-12-28%20at%2021.01.06.png" alt="Screenshot 2023-12-28 at 21.01.06.png" />

**Updated version**
<img width="1619" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFdOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0cd0fa598f60f210508aa0f81757a3b129de2556/Screenshot%202023-12-28%20at%2021.01.44.png" alt="Screenshot 2023-12-28 at 21.01.44.png" />

### RESOURCES
[Figma Link](https://www.figma.com/file/0foDnrR5AX93zzXI0t4eMR/V3_NEW?type=design&node-id=17054-48291&mode=design&t=hP6EGFkdONezecoW-0)

**Comment by sebas-led** [comment]
@laskokonopa Could you create a variation of the error page for a 500 code? Would it have 2 worlds or just normal 500?

**Comment by laskokonopa** [comment]
@sebas-led Hmm I'll try it both ways with the worlds and without and see if it works for this use.

**Comment by AhmadForhat** [comment]
@laskokonopa @kateinvan @sebas-led @Mica-pfl @ecurtosi99 

Please test this ticket when you have time

https://tblv3-staging.herokuapp.com/500
https://tblv3-staging.herokuapp.com/404
https://tblv3-staging.herokuapp.com/401

https://tblv3-kitchen-staging-c94ff87374cd.herokuapp.com/404
https://tblv3-kitchen-staging-c94ff87374cd.herokuapp.com/500
https://tblv3-kitchen-staging-c94ff87374cd.herokuapp.com/401

**Comment by kateinvan** [comment]
LGTM

**Comment by growebux** [comment]
@laskokonopa Thanks, I will decrease the size a bit.

**Comment by sebas-led** [comment]
@growebux Look great ! Thanks :)
