### ISSUE TITLE
Guide & Travel Agent Accounts | Restrict access for inactive guides/travel agents

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#173]
## SUMMARY
Once a guide or travel agent gets status inactive, we should remove access to the kitchen  or application for that account type.

### ACS

- [x] Prevent inactive guides to access kitchen for guides or application
- [x] Prevent inactive travel agents to access kitchen for travel agents or application
- [x] Prevent inactive travellers to access the marketplace
- [x] Prevent inactive TBL Staff to access Admin

**Comment by miyabitanimchi** [comment]
@sebas-led @Mica-pfl @ecurtosi99 @kateinvan @laskokonopa 
Please QA this ticket when you have time, 

If you don't have inactive account, you can also use:

- Inactive Traveller: miya-inactive-t@tblinternal.com
- Inactive Guide: miya-inactive-g@tblinternal.com
- Inactive Travel Agent: miya-inactive-ag@tblinternal.com
- Inactive Administrator: miya-inactive-ad@tblinternal.com
- Password: Miya123! for every email

- MP: https://tblv3-test.toursbylocals.com/login
- Kitchen: https://kitchen-test.toursbylocals.com/login
- Admin: https://admin-test.toursbylocals.com/login

Thank you!

**Comment by kateinvan** [comment]
LGTM!
just wondering, as a Travel Agent, they can access on Marketplace only through Kitchen, right?
so, once their account is inactive on Kitchen it would prevent access to the Marketplace as well.

**Comment by miyabitanimchi** [comment]
@kateinvan Thank you Kate, yes guides and travel agents can only login through Kitchen. 
For logging in on Marketplace, only users who have customer(traveller) squad (not inactive) can do it

I'll share conversation made by @sebas-led and I the other day
<img width="1154" alt="Screenshot 2024-04-17 at 2 43 19 PM" src="https://github.com/toursbylocals/wiki/assets/69213541/9dfeeda3-c0d8-4c68-b86b-509f51f3ce7e">

(@sebas-led I did a piece of ACS on this ticket https://github.com/toursbylocals/tblv3-api/issues/979 as it's related and was just adding a few line of code to do it. )

**Comment by sebas-led** [comment]
LGTM

**Comment by ecurtosi99** [comment]
LGTM
