### ISSUE TITLE
Country dropdown | Enhancements

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#174]
## SUMMARY
We use the Country dropdown in many places among the App (Marketplace, Kitchen, Admin). However, in some cases it's sorted alphabetically and in other is not. In addition, user cannot use the keyboard to choose a letter and be brought to that place.

### ACS

- [x] Make sure the migration of country covers the alphabetical order on each dropdown that has country
- [x] Allow user to type a letter and bring them to the first country in the list

**Agency Settings - Kitchen**
<img width="1496" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOCtqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6dc3bfc336c1e5b2fabcc71d77ce59dea2661dda/Screenshot%202024-01-05%20at%2018.04.45.png" alt="Screenshot 2024-01-05 at 18.04.45.png" />

**Traveller Personal Information - Marketplace**
<img width="1792" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUNqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b2417921a5766cb49b5834868e3eae81cc4ecef/Screenshot%202024-01-05%20at%2018.09.28.png" alt="Screenshot 2024-01-05 at 18.09.28.png" />

**Tour Traits - Admin**
<img width="1690" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUtqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--143fe4957d7f99c2c6b47b43b134b8ae12c56bac/Screenshot%202024-01-05%20at%2018.10.23.png" alt="Screenshot 2024-01-05 at 18.10.23.png" />

**Comment by growebux** [comment]
I am trying to clarify the agile principles to help us accurately measure time and effort for supposed deadlines. :)

Based on the requirements, what did I identify from this task? How can I suggest a more consolidated Agile approach?

--

**Subject of the task** Guidance for Implementing New "Select" Component Across Platforms

Summary

As we embark on introducing the "Select" component, aimed at enhancing our user experience with a searchable country dropdown, it's crucial we follow a structured approach. I'm outlining the key steps as user stories, to ensure everyone's on the same page and to facilitate a smoother workflow.

**User Stories & Responsibilities:**

1. **For the Design Team:**  
   - **User Story:** As a user, I want an intuitive and aesthetically pleasing "Select" component, so I can easily search and select countries.
   - **Task:** Provide detailed design specifications for the "Select" component.

2. **For the DSTBL Integration Team:**  
   - **User Story:** As a developer, I need a standardized "Select" component in our design system, so it can be reused across applications consistently.
   - **Task:** Integrate the new component into DSTBL following the design specs.

3. **For the Frontend Development Team:**  
   - **User Story:** As a user, I expect the "Select" component to work seamlessly, with features like sorting and keyboard navigation.
   - **Task:** Implement the "Select" component in applications, ensuring it adheres to the provided specifications and enhances user interaction.

4. **For the Testing Team:**  
   - **User Story:** As a user, I need the "Select" component to function correctly in every application it's implemented, ensuring my selections are accurately captured and reflected.
   - **Task:** Thoroughly test the component in various scenarios across all applications, ensuring each request and interaction is handled correctly.

**Next Steps:**  
The Design Team is requested to initiate this process by providing the necessary specifications. Each team will then follow through with their respective tasks, ensuring timely updates and coordination through our project management tools.

@kateinvan @laskokonopa @sebas-led @Mica-pfl @ecurtosi99 

What are your thoughts and what should I do? Thanks :)

**Comment by sebas-led** [comment]
We talked with @growebux and we already have the select component on DSTBL that fulfills the requirements in this task

**Comment by growebux** [comment]
@laskokonopa @kateinvan @sebas-led @ecurtosi99 

Could you review it?

TBLV3: https://tblv3-staging.herokuapp.com/

admin-test-agent@test.qa
Rafael123!

KITCHEN: https://tblv3-kitchen-staging-c94ff87374cd.herokuapp.com/login

admin-test-agent@test.qa
Rafael123!

ADMIN: https://tblv3-admin-69daefb91bda.herokuapp.com/login

ahmad.admin@toursbylocals.com
Ahmad123!

**Comment by sebas-led** [comment]
@growebux Thanks for the hard work. A couple of pages are still showing the previous implementation. Could you replace them there too?
- Become a Guide > https://tblv3-staging.toursbylocals.com/become-a-guide/registration
- Become an Agency > https://tblv3-staging.toursbylocals.com/become-a-travel-agency/registration
- Kitchen > Guide Account > Personal Information

All the rest looks amazing, thanks so much !

**Comment by kateinvan** [comment]
LGTM it's a big improvement to enhance the user experience :)

**Comment by growebux** [comment]
@sebas-led Sure, I will add them

**Comment by growebux** [comment]
@sebas-led I applied the changes here:

https://github.com/toursbylocals/tblv3/pull/1483%20

https://github.com/toursbylocals/kitchen/pull/332

**Comment by sebas-led** [comment]
@growebux I still see the old component on the three places shared. Do you need to merge into staging still?

**Comment by growebux** [comment]
@sebas-led I just deployed it, sorry about the delay.

**Comment by laskokonopa** [comment]
@growebux Works great. LGTM

**Comment by sebas-led** [comment]
Thanks Rafa ! LGTM
