### ISSUE TITLE
Booking Management Admin | Edit Booking

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#178]
## SUMMARY
Admin Staff can edit any field in a booking confirmation page. For that, they would access the `Booking Confirmation` page on the `Marketplace` from `Admin App`, which would give them full rights over the booking. There will be an `EDIT` CTA on the left panel that would redirect to the edit mode. The UI was done on the following [TICKET](https://github.com/toursbylocals/dstbl/issues/831)

We have implemented a very similar approach for Guides on Kitchen where they can edit only the first 4 fields under this [TICKET](https://github.com/toursbylocals/tblv3/issues/408)

Fields editable:
- Tour Date: Calendar picker to choose start date (single date selector, same as on Tour Details)
- Start Time: Dropdown (same as on Tour Details)
- Amount of travellers on tour: Int input
- Meeting Location
   - I want to meet at: Autocomplete with address (same as on Request Booking)
   - Meeting point description: Input field
- Overview, Itinerary, What's Included, What's Extra, Transportation (method, category and description) should all be the same as on Tour Editor
- Price (related account entry) > When clicking on Edit is out of scope as it's covered in a different ticket

### ACS

- [ ] Make sure the information displayed is the one from the booking
- [ ] Make sure the validations from tour.snapshot are the same (max characters on each field)
- [ ] Make all fields mentioned above editable
- [ ] Show a confirmation popup when saving changes
- [ ] Show a confirmation popup when clicking `BACK` without saving changes
- [ ] Once changes are implemented, we don't need to send any email but only update the booking data
- [ ] When it's a booking with tblLogistics = TRUE, show warning message on page and popup as on `Figma`

### VISUALS
<img width="1424" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODhsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--982091ca6ab8567c03c95ac1a5effd22626771cb/Screenshot%202024-02-02%20at%2013.02.35.png" alt="Screenshot 2024-02-02 at 13.02.35.png" />

<img width="1415" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUFsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--adf787c9de3aca672cbd291cf63e191e1656a33b/Screenshot%202024-02-02%20at%2013.02.49.png" alt="Screenshot 2024-02-02 at 13.02.49.png" />

<img width="1417" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUVsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf42fe5fadcf346d29a85110b80de84bd76925e2/Screenshot%202024-02-02%20at%2013.03.02.png" alt="Screenshot 2024-02-02 at 13.03.02.png" />

<img width="1423" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU1sQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a083feaf2cae5b55b49d64bd2c4a1125e1ee0b12/Screenshot%202024-02-02%20at%2013.03.16.png" alt="Screenshot 2024-02-02 at 13.03.16.png" />

### RESOURCES
[Figma Prototype](https://www.figma.com/proto/lvfNlIb7htglSgYxMYIlpQ/Admin?page-id=234%3A2253&type=design&node-id=9399-130679&viewport=3553%2C843%2C0.5&t=zn9r8as7tDCnzCwg-1&scaling=contain&starting-point-node-id=9529%3A208189)
[Figma Prototype for Edit Meeting Location with v2 data](https://www.figma.com/proto/lvfNlIb7htglSgYxMYIlpQ/V3_Admin?page-id=234%3A2253&type=design&node-id=11424-42012&viewport=646%2C-1321%2C0.25&t=2bCgRj73wPG15e5S-1&scaling=contain&starting-point-node-id=11424%3A42044&show-proto-sidebar=1)
[Figma Prototype for Logisitcs Bookings](https://www.figma.com/proto/lvfNlIb7htglSgYxMYIlpQ/Admin?page-id=234%3A2253&type=design&node-id=10674-34839&viewport=-1193%2C1017%2C0.5&t=44gABQl7FsBsZDN1-1&scaling=min-zoom&starting-point-node-id=10674%3A34839&show-proto-sidebar=1&mode=design)

**Comment by AhmadForhat** [comment]
@laskokonopa @sebas-led @Mica-pfl @ecurtosi99 @kateinvan 

Please test this ticket when you have time

https://admin-staging.toursbylocals.com/bookings/65dcd4724d2104abd9b3b086/details

ahmad.admin@toursbylocals.com
Ahmad123!

**Comment by kateinvan** [comment]
@AhmadForhat
- could you make Overview, Itinerary, What's included(select all that apply), What's extra(select all that apply) to h2?
@sebas-led 
- Anatoly is working on Tour editor fix, so after that, it would apply for this page as well? I can update Admin design as Tour editor.

**Comment by sebas-led** [comment]
@kateinvan Yes, please. Also, I couldn't find `Duration` in the edit mode. Could you check?
@AhmadForhat 
- The drop down for `Transportation Category` is always returning the options for "Public Transportation" under `Transportation Method` while it should change based on the selection, same as on Tour Editor. Could you check?

**Comment by kateinvan** [comment]
@sebas-led it wasn't on wireframe. do you want me to add Tour Duration?

**Comment by AhmadForhat** [comment]
@kateinvan I don't think is a good idea to change the HTML tag to h2, text is a label, which is important to accessibility, but I can change the font size and font weight. Should we have different label sizes in the design system?
