### ISSUE TITLE
Booking Management Admin | Report Changes by Admin flow

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#179]
## SUMMARY
When a booking has some changes or things to be reported to ToursByLocals, the booking status is changed to `REPORTED`. This could happened in 3 ways:
- Guide reports a booking from Kitchen > Done [HERE](https://app.zenhub.com/workspaces/rd-team-61a6bf56a3b924001cb03cba/issues/gh/toursbylocals/tblv3/849)
- Booking is marked as reported automatically after 72hs if guide doesn't completed on Kitchen > Done [HERE](https://app.zenhub.com/workspaces/rd-team-61a6bf56a3b924001cb03cba/issues/gh/toursbylocals/kitchen/166)
- Admin Staff can manually change the booking status to reported

This ticket is to create the flow for the 3rd option, in which Admin Staff will need to provide the details for why the booking is changing to reported.

### ACS

- [ ] Create the flow for Admin Staff to change a booking status to Reported
- [ ] Create page for inputting the details of the report changes as per `Figma` design
     - Reason: reasonProblem
  - [ ]  Create popup to confirm booking status change to Reported including referenceCode and Tour Title
  - [ ]  Create popup confirmation when booking status was successfully changed to reported. After closing, take user back to Booking Confirmation

### VISUALS
<img width="1420" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUFtQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aaa23eaee9bee287533f8598cf1c44d6cec5ef59/Screenshot%202024-02-02%20at%2015.42.40.png" alt="Screenshot 2024-02-02 at 15.42.40.png" />

<img width="1404" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUVtQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eed337179c4fadf657e72a96f773a8fcf5e6d44c/Screenshot%202024-02-02%20at%2015.42.53.png" alt="Screenshot 2024-02-02 at 15.42.53.png" />

<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUltQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--968d0e88a398b0a01ef3c2cc2dedecdd6e8f6976/Screenshot%202024-02-02%20at%2015.43.06.png" alt="Screenshot 2024-02-02 at 15.43.06.png" />

### RESOURCES
[Figma Prototype](https://www.figma.com/proto/lvfNlIb7htglSgYxMYIlpQ/Admin?page-id=2982%3A76793&type=design&node-id=2982-77028&viewport=213%2C446%2C0.08&t=7I6Utdom9JnvpYiy-1&scaling=contain&starting-point-node-id=2982%3A76875)

**Comment by AhmadForhat** [comment]
@sebas-led @Mica-pfl 

is this a new status?

we used to have these ones:

export enum BookingStatusEnum {
  Pending = 'PENDING',
  NotResponded = 'NOT_RESPONDED',
  DeclineInProgress = 'DECLINE_IN_PROGRESS',
  Declined = 'DECLINED',
  Accepted = 'ACCEPTED',
  Confirmed = 'CONFIRMED',
  CancelInProgress = 'CANCEL_IN_PROGRESS',
  Cancelled = 'CANCELLED',
  ChangesReported = 'Changes_Reported', //problem
  Incomplete = 'INCOMPLETE',
  Completed = 'COMPLETED'
}

I think the one that you're talking about is Changes Reported

**Comment by sebas-led** [comment]
LGTM
