### ISSUE TITLE
Live Chat Integration | Add javascript integration on Staging and Production 

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#181]
## SUMMARY
We have a Live Chat integration via NectarDesk that is active on every `MARKETPLACE` page, for both auth and non-auth users.

In order to run the integration, we need to copy and paste the javascript to the head section of the web page. The design, colours, settings, etc are all handled directly on Nectar Desk.

### ACS

- [x] Add Live Chat on Staging
- [x] Add Live Chat on Production

### RESOURCES
- Production: <script type=“text/javascript” src=“https://toursbylocalsaccount.nectardesk.io/chat/embed/1”></script>
- Staging/Testing: <script type=“text/javascript” src=“https://tbltraining.nectardesk.io/chat/embed/2”></script>

### CREDENTIALS TO TEST
URL: https://tbltraining.nectardesk.io/
Login: [sleder@toursbylocals.com](mailto:sleder@toursbylocals.com)
Password: q73sUHrgjR

**Comment by growebux** [comment]
Could you review?

Link: https://tblv3-staging.herokuapp.com/

**Comment by sebas-led** [comment]
LGTM for the scope of this ticket. Once we validate with Ops, we will probably need to see how to make it work in a better way on mobile as it overflows the bottom navbar. As said, out of scope so this LGTM
