### ISSUE TITLE
Messaging System | QA comments and bugs

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#182]
## SUMMARY
When doing QA of the Messaging System, we encounter a few things not working as expected and/or bugs that require attention and fixes:

- [Actionable Widgets](https://github.com/toursbylocals/messenger-api/issues/7)
   - Send Customer Support Link needs to return /help instead of /contact-us
   - Tours, Available Guides & Custom Tours are not returning any items for v2 guides
- [Create flow for starting a chatroom](https://github.com/toursbylocals/wiki/issues/161) 
   - When attaching an image, it's not possible to click on it to open the file, which would make images very small. It does work for pdf documents tho. Could you check?
   - The calendar icon is showing always and clicking on it doesn't lead anywhere. The icon should display only if there is an upcoming booking between users and clicking on it should redirect to the booking confirmation in a new tab. Could you check?
   - could you use the same data picker on the Tour Detail page? The current one looks a bit different
   - could you make date and party size field in two lines like Figma design on mobile view? currently, the data picker is cut off.
   - could you change the default subject text to 16px, 500 weight? you followed Figma design, but now that I saw it, it looks a bit bigger than Figma. sorry about that
- Guide view of Messaging System
   - For some reason, it always ends up on an Application error. Sometimes user can navigate but as soon as a new message is sent to the guide, it automatically goes to Application error.
   - When it worked, guide id_65aee3bab883ddd442039980 was used. There were several chatrooms that don't belong to the guide, the list of Other guides in your area, tours and custom tours were returning no results but the guide should have results on all of them 
   - Bookings completed on traveller's heading is always returning 0. Could you check?

 
## TICKET IN PROGRESS AS WE CAN QA PROPERLY

**Comment by sebas-led** [comment]
@AhmadForhat @Trs-24 This ticket has an open PR, cannot be in QA yet

**Comment by sebas-led** [comment]
@ecurtosi99 @Mica-pfl @kateinvan @laskokonopa Could you please QA the entire messaging system?
Guide credentials:
sleder+guideInFrance2@tblinternal.com
Test123!

Traveller credentials:
sleder+1000@tblinternal.com
Test123!

That way, you can send messages back and forth using both accounts.

You can also use the Traveller credentials and send a message to any guide in the Marketplace to see the flow.

**Comment by sebas-led** [comment]
@Trs-24 As shared on Slack, this are my remaining QA points:
- Custom Tours on actionable widgets CTA: "Edit Tour" should be "Send Tour" > Brings the URL of the custom tour selected, same as with `Tours` under actionable items > Currently, it shows Edit Tour which redirects to https://tblv3-test.toursbylocals.com/guide/undefined/guide/new-tour/customtour/65fa066e6525a6c3d8e3e7e3 which is a 404
- Notification icon is missing on Guide Account when user has new messages
- When user clicks on any link in the messaging system, it should open in a new tab, currently opens in the same tab
- URLs are all having double bars like https://tblv3-test.toursbylocals.com//policy/toursbylocals-cancellation-policy
- User cannot save notes

**Comment by laskokonopa** [comment]
When sending files only the icon activates the sends not when you click on the labels ie:Send PDF. Also cant save notes. I also get a 404 when sending message from tours.

<img width="383" alt="Screenshot 2024-03-25 at 2 12 31 PM" src="https://github.com/toursbylocals/wiki/assets/134641824/1d185a10-5e64-4933-b719-8dc939cc4834">

**Comment by kateinvan** [comment]
same comment as Lasko and Seba.

**Comment by ecurtosi99** [comment]
no further comments. rest LGTM
