### ISSUE TITLE
Wiki - Development Lifecycle Guide

### ISSUE THREAD

**Issue by DongJoSuh** [toursbylocals/wiki#21]
@growebux commented on [Tue Jun 14 2022](https://github.com/toursbylocals/dstbl/issues/200)

Create Development Process Guide:

ACS:

- [x] Onboarding Initiative
- [x] Initiative Analysis / Evaluation
- [x] Epics / Stories 
- [x] Grooming
- [x] Planning
- [x] Coding
- [x] Testing
- [x] Reviewing
- [x] QA'ing
- [x] Release

---

@growebux commented on [Mon Jun 27 2022](https://github.com/toursbylocals/dstbl/issues/200#issuecomment-1167639769)

@DongJoSuh Joe, when you start this task could you create a pull request and attach it?

**Comment by DongJoSuh** [comment]
repo was set to dstbl so i used 'Move issue' button to move the ticket to wiki. It copies the ticket to wiki and close the old one by itself. 'Transfer issue' was not showing wiki repo for some reason.

**Comment by growebux** [comment]
@DongJoSuh Joe, when you start this task could you create a pull request and attach it?
