### ISSUE TITLE
Document the feature request review process

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#29]
**Summary**
We recently created the slack channel hooks for feature request. Now, we need to describe and document the process for when a new request is done.

**ACS**

- [x] Create a document with flow for feature requests since they are submitted by any department member until they are released and/or rejected.

**Comment by sebas-led** [comment]
@Mica-pfl @growebux @codedavinci Leaving the process map here to be used on the Slack Channel with everyone outside of the department. Let me know your thoughts.
[R&D Request Flow-R&D Request Flow V3.pdf](https://github.com/toursbylocals/wiki/files/9153693/R.D.Request.Flow-R.D.Request.Flow.V3.pdf)

**Comment by growebux** [comment]
Sure, thanks @sebas-led

**Comment by growebux** [comment]
@sebas-led I am checking your Request Flow now and I will get back to you soon.

**Comment by codedavinci** [comment]
How's the status of this ticket, @sebas-led @Mica-pfl  ?

**Comment by codedavinci** [comment]
LGTM Closing this ticket
