### ISSUE TITLE
SPIKE - Financial buckets

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#30]
**Summary**
Based on feedback from stakeholders, we would require to have financial buckets, not related to bookings, to assign different payments such as when we get a cancellation with full refund to travellers and payment to guides or the guide relief fund or any other buckets we could consider.

**ACS**

- [x] Create a business case

- [ ] Share with stakeholders (Accounting, PM, DV) to consider the current buckets required and thresholds needed

**Comment by sebas-led** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RD-team-61a6bf56a3b924001cb03cba/issues/toursbylocals/wiki/30?planning-poker) with ZenHub @codedavinci @DongJoSuh @ecurtosi99 @growebux @jeannejx @Vinnie1959

**Comment by sebas-led** [comment]
LGTM

**Comment by codedavinci** [comment]
Already reviewed this, we might come back to this but we cross the bridge when we get there. LGTM for now.
