### ISSUE TITLE
SPIKE - Thresholds for Pay Out Methods

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#31]
**Summary**
It was decided that we would have the option to request payment at any point for Suppliers instead of batch payments every Wednesday to all suppliers together.

**ACS**

- [x] Research with accounting for minimum thresholds for each Pay Out Method
- [x] Determine who is taking the the transaction fee (supplier or TBL)

- [x] Document the results and include in the Supplier Model for PayOutMethod

**Comment by sebas-led** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RD-team-61a6bf56a3b924001cb03cba/issues/toursbylocals/wiki/31?planning-poker) with ZenHub @codedavinci @DongJoSuh @ecurtosi99 @growebux @jeannejx @Vinnie1959

**Comment by DongJoSuh** [comment]
Payment Method:
- Check:
	Description: Cost per payment: $5. This is an option if you are located in Canada or the USA.
	Transaction Fee: 
	- 5 CAD
	- 5 USD
	Requirements:
	- Direct Payment Beneficiary Name
	- Check Address

- Direct Deposit:
	Description: Cost per payment: $1 in the USA and Canada, 1 EUR in the Euro zone, 1 GBP in the UK. This is an option for payments to North America, Europe and the UK. Funds are deposited directly to your bank account within 2 to 3 days and no other fees are charged.
	Transaction Fee: 
	- 1 CAD (Free threshold: 1800)
	- 1 EUR (Free threshold: 1300)
	- 1 GBP (Free threshold: 1100)
	- 5 MYR (Free threshold: 6000)
	- 1 USD (Free threshold: 1500)	
	Requirements:
	- Direct Payment Beneficiary Name
	- IBAN / BIC (SEPA - Must be EUR)
	- Transit Number & Financial Institution Number & Account Number (Canada - must be CAD)
	- Routing Number & Account Number (USA - must be USD)
	- Sort Code 1 & Sort Code 2 & Sort Code 3 & Account Number (UK - must be GBP)
	- Financial Institution Number & Account Number (Malaysia - Must be MYR)

- Payoneer:
	Description: Cost per payment: free. Note that Payoneer will charge a fee (min $2 each time it is loaded). You can withdraw the funds to your bank account or request a ToursByLocals MasterCard which you can use it as a normal credit card or withdraw funds from an ATM. Contact your ToursByLocals guide manager to get further details. To use Payoneer, your preferred currency must be USD.

- PayPal:
	Description: Cost per payment: $2 USD or approximate equivalent in your payment currency. PayPal is a good choice in many countries, but it does not work everywhere. There is no cost to withdraw funds from your PayPal account into your bank account (subject to certain limits).
	Transaction Fee:
	- 3 AUD
	- 3 CAD
	- 2 CHF
	- 15 DKK
	- 2 EUR
	- 2 GBP
	- 300 JPY
	- 3 NZD
	- 20 SEK
	- 3 SGD
	- 2 USD
	Requirements:
	- Payment Email

- Wire Transfer:
	Description: Cost per payment: $10 USD (or equivalent in other currencies). A wire transfer is deposited directly into your account. Note that your bank may also charge you a fee to receive the payment.
	Transaction Fee:
	- 14 AUD
	- 14 CAD
	- 10 CHF
	- 65 DKK
	- 9 EUR
	- 8 GBP
	- 1100 JPY
	- 40 MYR
	- 15 NZD
	- 675 RUB
	- 90 SEK
	- 14 SGD
	- 10 USD
	Requirements:
	- Direct Payment Beneficiary Name
	- Beneficiary Bank SWIFT Code
	- Beneficiary Bank Account Number / IBAN
	- Payment Instruction
	- Wire Transfer Address
	

(Supports all Guides, Agencies and Affiliates)

**Comment by DongJoSuh** [comment]
@sebas-led @Mica-pfl here are the current payout method. Please use this to finalize tbl v3 payout method. Let me know if you have any questions.

**Comment by Mica-pfl** [comment]
https://docs.google.com/document/d/1k4ufpuDqgMVKEeUV_QD10ZI_51cuENb_gf5jIl_ahNM/edit?usp=sharing

**Comment by Mica-pfl** [comment]
TBL will taking transaction fees, App PM

**Comment by sebas-led** [comment]
What's the status of this ticket? Is there anything missing to close it?

**Comment by codedavinci** [comment]
LGTM. Outcome decided !
