### ISSUE TITLE
Wiki - Document all the requirements for PayFac Compliant Payment Processor

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#32]
**Summary**
We already did a spike to gather details on what's PayFac for ToursByLocals and also added assumptions/requirements on the models such as ability to pay multiple suppliers in a single booking or reduced transaction fees or an integrated wallet into the customer accounts. However, we haven't created a single document that compiles all the requirements (must have and nice to have) in order to determine which provider to choose as a business.

**ACS**

- [x] Create a single document with all the requirements, including pay in, pay out, compliance and business needs.

- [ ] Gather approval from stakeholders (Paul/Dave/Luciano/Augusto)

**Comment by sebas-led** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RD-team-61a6bf56a3b924001cb03cba/issues/toursbylocals/wiki/32?planning-poker) with ZenHub @DongJoSuh @ecurtosi99 @growebux @jeannejx

**Comment by Mica-pfl** [comment]
https://docs.google.com/document/d/1WOiXhBwUtN1vR_rTBCR1RpW9yRsmM0XIe6cCEam6Y2k/edit

**Comment by Mica-pfl** [comment]
Need to define payout supplier methods supported, TBD on product steering 09/08. May be icebucket
