### ISSUE TITLE
Spike - Adds-on Collection

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#33]
**Summary**
Currently, the what's included & what's extra contains most of the elements as open text. In the V3, we would like to remove that option by having all the possible adds-on listed in a dropdown menu for the Suppliers at the time of creating a listing. Listings will be considered only for the supplier (guide) services and everything else would be an add-on (ie: private transportation, entrance fees, food tasting, etc)

**ACS**

- [x] Gather data of all the common elements being added on What's Included & What's Extra on V2

- [x] Check with Tour Experience to review the list and add any missing adds-on

- [x] Review taxonomy with Tour Experience and UX/UI

**Comment by sebas-led** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RD-team-61a6bf56a3b924001cb03cba/issues/toursbylocals/wiki/33?planning-poker) with ZenHub @DongJoSuh @ecurtosi99 @growebux @jeannejx

**Comment by sebas-led** [comment]
Created the doc: https://docs.google.com/document/d/174ldFaly82HkcBsvzerhuP0Yor3RjKHn5pzWUihlDfc/edit#
Did also the analysis for What's Included & What's Extra but didn't finish that as it's not part of the scope. Will create a separate ticket to conclude with those sections and consider the findings from this one already to save time.

**Comment by Mica-pfl** [comment]
LGTM
