### ISSUE TITLE
Spike - Attributes-credentials for Suppliers

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#34]
**Summary**
Currently, suppliers can add as open text, anything they may want under 'credentials'. We need to standardize this in order to be consistent, allow comparison and specially, for filtering option after.

**ACS**

- [x] Gather all type of credentials or fields of expertise being used under credentials on V2.

- [x] Check with Tour Experience to ensure all the most important items are listed
- [x] Categorize the list of attributes

**Comment by sebas-led** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RD-team-61a6bf56a3b924001cb03cba/issues/toursbylocals/wiki/34?planning-poker) with ZenHub @DongJoSuh @ecurtosi99 @growebux @jeannejx

**Comment by sebas-led** [comment]
First draft created: https://docs.google.com/document/d/1LFtIHEsZkncfBbm7I3P8Nv05VZo_huCWH2q85MrHWE0/edit#
Will move it back to the To Do as Tour Experience needs until Monday to check with them

**Comment by sebas-led** [comment]
Luciano asked to validate one more thing with Augusto (legal) before we proceed. Will try to connect tomorrow as it's very late in BA already

**Comment by sebas-led** [comment]
@codedavinci Changes applied based on the meeting we had yesterday

**Comment by codedavinci** [comment]
Perfect @sebas-led  closing this ticket !
