### ISSUE TITLE
Wiki - Transportation Method supported repository

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#36]
**Summary**
Transportation method is an essential component on private tours since tours could be done by car, van, bus, boat, bike, helicopter, 4x4, etc. Suppliers currently have to manually input the type of transportation and details, which is not standardize, creating inconsistencies and not aligned with the v3 designs (showing the same icon for each transportation method)

**ACS**

- [x] Create a list of all transportation methods supported in v3

- [x] Validate with TX to ensure none are missing

**Comment by sebas-led** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RD-team-61a6bf56a3b924001cb03cba/issues/toursbylocals/wiki/36?planning-poker) with ZenHub @codedavinci @DongJoSuh @ecurtosi99 @growebux @jeannejx @martyhurl

**Comment by sebas-led** [comment]
Document created. Waiting for the validation with TX to get the final list: https://docs.google.com/document/d/15P06XAc__BCAUgXScA-TwAMCcNxRr_SctBT0sSLC0tk/edit#heading=h.a40ij9bltv4a

**Comment by sebas-led** [comment]
Simplified the process according to what we talked with Eddie. All body types included in a unique list and if no selection, it's a walking tour

**Comment by codedavinci** [comment]
LGTM
