### ISSUE TITLE
Spike - How to onboard an add-on

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#37]
**Summary**
We have determined that add-ons could be transportation, tickets and/or accommodation, which is mainly onboarded by logistics.

**ACS**

- [x] Document how to onboard a new add-on supplier for Transportation
- [x] Document how to onboard a new add-on supplier for Tickets
- [x] Document how to onboard a new add-on supplier for Accommodation

**Comment by sebas-led** [comment]
Meeting invite sent for Aug 30, 2022 with Mike (Logistics)

**Comment by Mica-pfl** [comment]
LGTM

**Comment by sebas-led** [comment]
@Mica-pfl @codedavinci Document updated with how it would be in v3. Please, take a look. Based on this document and what we talked the other day, I have added the initiatives into the roadmap as well (future initiatives)

**Comment by Mica-pfl** [comment]
LGTM with changes applied
