### ISSUE TITLE
SPIKE - Click wrap agreements

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#38]
**Summary**
There are multiple places in which we may require the users to agree to something (terms & conditions, privacy policy, etc), and currently are not consistent. In addition, in some cases we provide a checkbox to agree, in some others only the link or nothing at all.

**ACS**

- [x] Create a list of places where we should show the following items:
[ ] Terms & Conditions
[ ] Privacy Policy
[ ] Cancellation Policy
[ ] Agreements (Tour guide, travel agent, affiliate and gift card, shore excursion)

- [x] Validate with Legal

**Comment by Mica-pfl** [comment]
Sitemap shared with Augusto

**Comment by Mica-pfl** [comment]
https://docs.google.com/spreadsheets/d/14pXr4kIVwEHcwCpywYQvmnzku4KuVInft_OaPL2JlVU/edit#gid=1569813677

**Comment by Mica-pfl** [comment]
Proposed model:

[ - ] Accept Terms and Conditions, Privacy Policy and Cancelation Policy
[ - ] Accept to receive Marketing Emails

**Comment by codedavinci** [comment]
LGTM
