### ISSUE TITLE
Wiki - Identity Verification for Suppliers

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#39]
**Summary**
Guides currently apply to the site and go over an interview to become active in the marketplace. However, we are not doing any identity verification to ensure they are who they say they are. We used to have Refinitiv to check OFAC status, but we would like to have a broader verification of the guides in order to protect ToursByLocals and customers from all types of identity risk. It was decided that we would integrate with TruliooID, but we need all the documentation.

**ACS**
- [x] Create a document with all the processes and attributes to be verified and how to store the data

**Comment by Mica-pfl** [comment]
https://docs.google.com/document/d/1yo6j1rucXxhxCPHk1QKz61xVi4qA4DmxFiimUQ38RiA/edit

**Comment by Mica-pfl** [comment]
@sebas-led There is a part on suppliers driver records verification Augusto touched based on yesterday I included, fyi (related to the document "onboarding suppliers")

**Comment by sebas-led** [comment]
@Mica-pfl Supplier driver records is an initiative for after 3.0 and will be done once we do Logistic suppliers. The section was removed and moved to the how to onboard an add-on document.
@codedavinci Based on the document, it would mean that we will probably need to add a timestamp on 'verified' for Suppliers in order to run it again every 1 year, right?

**Comment by codedavinci** [comment]
if it becomes a business rule we can set a timer based on the verification.

**Comment by codedavinci** [comment]
LGTM
