### ISSUE TITLE
Wiki - Check in & Check Out Functionalities for Suppliers

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#40]
**Summary**
There is an idea to request Guides to check in when starting the tour and check out when finishing. 
Check in: When a booking is starting, it's very hard to determine what's going on since ToursByLocals is not in-person with the guides and travellers. Guides could be a no-show or late by an hour without us knowing or even have challenges to find the travellers at a cruise ship port, ending in a cancellation that could be prevented if warned. In addition, tours could be shorter or longer than the booking for several reasons without knowing unless there is a complaint.
Check out: At the end of a tour, Guides need to mark a tour as completed or problem. However, it could take up to 72hs for them to do so in the current system, prompting potential problems such as complaints or unpaid commissions. We are now considering the start time + duration of the tour to know when a tour is over, but in reality, the tour could still take place for 1 or 2hs extra hours.

**ACS**

- [x] Definition of Check in with implications

- [x] Definition of Check out with implications

- [ ] Validate with Operations & Tour Experience

**Comment by sebas-led** [comment]
LGTM

**Comment by codedavinci** [comment]
LGTM
