### ISSUE TITLE
SPIKE - Document all automatic email workflows (Marketplace only)

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#41]
**Summary**
There are several automatic email being generated as a result of a workflow with triggers. A starting point was created on https://docs.google.com/document/d/1URanE49HFMW2ZiyE6eeZPa-JfcrVrvRpW8E1S_HWLFI/edit but it's missing some or even the workflows that triggers each of them. In the roadmap, we are dividing them into the following:
- User interactions (account creation, new message, etc)
- Transactional (booking created, booking confirmed, etc)
- Upselling (shore excursion, refer a friend, etc)
- Changes to a booking (meeting location, date, time, etc)

**ACS**

- [x] Document all automatic email with their workflows and triggers (Marketplace only)

- [x] Validate with Dave/Joe/Marty

**Comment by sebas-led** [comment]
Asking Dave to share all the triggers and variables in the DB to start documenting and linking to the copy

**Comment by sebas-led** [comment]
- Index created with links to each automatic email and showing triggers, sender email, sender display name,  subject and email category (transaction, user interaction, change booking and upselling): https://docs.google.com/spreadsheets/d/1UYhNeFvj3iWPCjTL2ZHt-3ZKPS9eRY9LTLLdk_EGJRU/edit#gid=0
- Each automatic email doc contains the code and a sample in plain text
Note: Not moving the ticket to review as there are 5 automatic emails in my records that are pending the details. Checking with Dave about those

**Comment by Mica-pfl** [comment]
LGTM

**Comment by codedavinci** [comment]
LGTM, thank you very much for this @sebas-led  this is very helpful <3
