### ISSUE TITLE
Document the workflow for Reviews

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#42]
**Summary**
Guides will be able to check-out after the tour, which would trigger the workflow for travellers to leave a review. If users leave a <5 star review, QEM will need to be notified and additional details should be asked to the travellers before a guide is able to respond publicly. Needs to consider reviews in external sites (Google My Business, Truspilot & Verified Reviews).

**ACS**

- [x] Document the lifecycle of reviews since the tour is completed, including the business logic for when to request external reviews and QEM processes

**Comment by Mica-pfl** [comment]
https://docs.google.com/document/d/16yglj-GK_czexxOI2M7Ny1BLkyG2RHWbB2DhuS3w_Hc/edit

To be discussed in Product Steering meeting, proposed change in flow to be approved.

**Comment by codedavinci** [comment]
The only thing is missing is a deadline to send the review, my suggestion is 30 days, after that the review notification will disappear.

**Comment by codedavinci** [comment]
LGTM
