### ISSUE TITLE
Document workflow for recruiting

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#43]
**Summary**
Once a guide applies, we need to document exactly how it would work. Would they have direct access to certain modules in the dashboard to fulfill before a Guide Acquisition determines that they are a good fit and move to onboarding? Or they will need to fulfill a form to apply without any access?

**ACS**

- [x] Document the workflow for how guides are recruited in v3

**Comment by sebas-led** [comment]
https://docs.google.com/document/d/1tDbkVVPkzhoM2eR2i8MY7ci1IfoqDaP4CESXaO9r_Pk/edit#

**Comment by codedavinci** [comment]
L GREAT TO ME. Love this very streamlined process.
