### ISSUE TITLE
Standardize auto email fields (sender email, sender display)

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#45]
**Summary**
Currently, some emails go from support, others from Sara at ToursByLocals, other from Guide Name, etc. Moving into v3, it would be ideal if we could standardize and document the different fields of auto emails.

- [x] Document the sender email address and sender name display on Transactional emails
- [x] Document the sender email address and sender name display on User Interaction emails
- [x] Document the sender email address and sender name display on Booking changes
- [x] Document the sender email address and sender name display on Guide Messages
- [ ] Validate with Operations & Marketing

**Comment by sebas-led** [comment]
Received 25 type of emails that are sent automatically to travelers with the variations from Dave. Working on them to have triggers and samples

**Comment by sebas-led** [comment]
Check tab v3
https://docs.google.com/spreadsheets/d/1UYhNeFvj3iWPCjTL2ZHt-3ZKPS9eRY9LTLLdk_EGJRU/edit#gid=1003169846

**Comment by codedavinci** [comment]
LGTM
