### ISSUE TITLE
Messaging System - Header for Guides

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#48]
**Summary**
In the messaging system, when a guide is logged, they will find all the contacts with whom they exchanged messages with. Along with the name of the customer, they need to have further details to help with conversion, which needs to be defined. 

**ACS**

- [x] Document type of traveler (prime, vip, new)

- [x] Document traveler's score

- [x] Validate with TX

**Comment by Mica-pfl** [comment]
https://docs.google.com/document/d/1J2G98ZZHf2cP8sbHTzLPxhy_mzWsBFPNg75ZFmvLkac/edit#

**Comment by sebas-led** [comment]
LGTM

**Comment by codedavinci** [comment]
LGTM
