### ISSUE TITLE
Messaging System - Header for Travelers

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#49]
**Summary**
In the messaging system, when a customer is logged, they will find all the guides with whom they exchanged messages with. Along with the name of the guide, they need to have further details to prompt towards conversion, which needs to be defined. 

**ACS**

- [x] Document fields to be included (rating average, review count, areas of expertise, work locations?)

- [x] Validate with Operations

**Comment by Mica-pfl** [comment]
https://docs.google.com/document/d/1J2G98ZZHf2cP8sbHTzLPxhy_mzWsBFPNg75ZFmvLkac/edit#

**Comment by Mica-pfl** [comment]
@sebas-led I tried getting a count on amount of bookings completed by Ts to give them tires, my Mac has crashed 521 times. Could you try on your end? Amount of tours completed still works for me and Tx.

**Comment by codedavinci** [comment]
LGTM, @sebas-led  please double check as well :)

**Comment by sebas-led** [comment]
LGTM
