### ISSUE TITLE
Step #3 Training - Egghead

### ISSUE THREAD

**Issue by bottbl** [toursbylocals/wiki#5]
- [x] Styled Components
- [x] Styling React Applications with Styled Components 

- [x] Fundamentals of Redux Course from Dan Abramov

- [x] Modern Redux with Redux ToolKit (RTK) and TypeScript
- [x] GraphQL Query Language

**Comment by DongJoSuh** [comment]
@growebux how are you doing with videos? can you comment the topic you have finished?

**Comment by growebux** [comment]
Thanks @DongJoSuh I forgot to mention that here.

I studied the class "Styled Components and Styling React Applications with Styled Components" yesterday.

**Comment by DongJoSuh** [comment]
finished all 5 videos

**Comment by martyhurl** [comment]
I have completed all videos

**Comment by martyhurl** [comment]
@growebux @jeannejx Please communicate between yourselves and check off the videos as completed

**Comment by jeannejx** [comment]
> @growebux @jeannejx Please communicate between yourselves and check off the videos as completed

Started to watch "styled component".

**Comment by growebux** [comment]
watched Fundamentals of Redux Course from Dan Abramov

**Comment by growebux** [comment]
watching Modern Redux with Redux Toolkit (RTK) and TypeScript

**Comment by growebux** [comment]
I have completed all videos

**Comment by jeannejx** [comment]
Done watching all videos.
