### ISSUE TITLE
Wiki - Document Reports for Operation & Marketing Dashboards

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#50]
**Summary** 

Currently Operations & Marketing work with weekly reports on Data Studios to review different metrics. Create a unified document with all metrics and reports needed for their daily tasks to include as Dashboard reports in kitchen V3. 

**ACS**

- [x] List all existing Data Studios and their purpose
- [x] List all metrics for Operations
- [x] List all metrics for Marketing

**Comment by sebas-led** [comment]
https://docs.google.com/spreadsheets/d/1752Jpm8mB4KhQOKvYN2fBGEejQRAWNTWhv9gp8WaJlI/edit#gid=23098641
Reviewed by Geneva (Ops), Gavin (QEM) and Nikki (MKT)

**Comment by Mica-pfl** [comment]
LGTM

**Comment by codedavinci** [comment]
LGTM
