### ISSUE TITLE
Document First-Party Cookies

### ISSUE THREAD

**Issue by Mica-pfl** [toursbylocals/wiki#52]
@Mica-pfl commented on [Tue Oct 11 2022](https://github.com/toursbylocals/dstbl/issues/378)

**Summary**

First-party cookies are directly stored by the website visited. These cookies allow website owners to collect analytics data, remember language settings, and perform other useful functions that provide a good user experience.

**ACS**

- [ ] Document attributes we want to store based on first party cookies
- [ ] Validate with Management and MKT

**Comment by sebas-led** [comment]
https://docs.google.com/document/d/1N3pRqrAGCPv8f_WdmdemK-PW7HCz0RmLQ47omET02EY/edit#

**Comment by codedavinci** [comment]
LGTM
