### ISSUE TITLE
Document Third-party cookies

### ISSUE THREAD

**Issue by Mica-pfl** [toursbylocals/wiki#53]
@Mica-pfl commented on [Tue Oct 11 2022](https://github.com/toursbylocals/dstbl/issues/379)

**Summary**

Third party cookies are created by domains that are not the website (or domain) visited. These are usually used for online-advertising purposes and placed on a website through a script or tag. 

**ACS**

- [ ]  Document third party cookies needed
- [ ]  Validate with Management and MKT

**Comment by sebas-led** [comment]
https://docs.google.com/document/d/1N3pRqrAGCPv8f_WdmdemK-PW7HCz0RmLQ47omET02EY/edit#
