### ISSUE TITLE
Document Cruise Lines & Cruise Ships for Shore Excursion

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#54]
**Summary**
The Shore Excursion page will offer users a selection of their cruise line and cruise ship to get the itinerary and ports of call. We need to determine which cruise lines and which cruise ships from each cruise line we will support.

**ACS**

- [x] Document cruise lines supported

- [x] Document cruise ships supported

**Comment by sebas-led** [comment]
https://docs.google.com/document/d/1vfo_-h__YKAfNKznoGNbZQlD9olkEV5BvBwkW10sG4o/edit#

**Comment by Mica-pfl** [comment]
LGTM
