### ISSUE TITLE
Trigger Words for Messages

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#56]
**Summary**
In the messaging system, there will be certain trigger words that would make the message to be automatically blocked and flagged to Operations. Those cases involve poaching our guides by competitors, sexual content, etc.

**ACS**

- [x] Create a list of all trigger words needed to be blocked

- [x] Validate with Operations

**Comment by Mica-pfl** [comment]
Asked Dave for list of trigger words in V2

**Comment by Mica-pfl** [comment]
https://docs.google.com/spreadsheets/d/1n9K42LKTJFg_7q-Gyc0VBlqAnvhFS_qTg05zaL68nD4/edit#gid=0

Shared list with Ops to be reviewed by friday 4th

**Comment by Mica-pfl** [comment]
Confirmed with Dave, no rules regarding confirmed bookings or attachments are applied currently to suspended messages. 

Meeting with ops for communication 16/11

**Comment by sebas-led** [comment]
@Mica-pfl Can we have a meeting with Geneva about this topic? It doesn't make much sense to me for all the suspended KW requested. Maybe together with @codedavinci so that we can all understand what they are trying to achieve with having all those KW suspended. It looks like the are trying to mirror almost the same as in v2 to me...

**Comment by codedavinci** [comment]
@sebas-led  Okay  I'll be there

**Comment by Mica-pfl** [comment]
@sebas-led @codedavinci sure, yes they want to keep parity with V2. Keep in mind that these only suspend before a booking for the traveler is confirmed, after a booking is confirmed they would not be suspended. I'm ok with involving Geneva if you want to trim them

**Comment by codedavinci** [comment]
OK, LGTM

**Comment by sebas-led** [comment]
LGTM
I guess we will need to find a list of the words to include on each of those categories (ie: What might be sexual content or illegal sexual behaviour)

**Comment by codedavinci** [comment]
Yes, anyway we can always customize this.
