### ISSUE TITLE
SPIKE - Google Tag Manager Analytics

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#57]
**Summary**
We have a Google Tag Manager integration in v2 that will need to remain in v3. In order to do that, we need to understand how it's implemented and how it works.

**ACS**

- [x] Document the integration with Google Tag Manager in v2

- [x] Validate with Marketing

**Comment by sebas-led** [comment]
Data Layers + Google Tag Manager Setup: https://docs.google.com/spreadsheets/d/1h2oiXqXCupC4v3i0cqHaLNCSWqTL79AN-I_bpjdR5TU/edit#gid=0

**Comment by codedavinci** [comment]
LGTM
