### ISSUE TITLE
Google Analytics (GA4) Integration

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#58]
**Summary**
We have a Google Analytics integration in v2 that will need to remain in v3. In order to do that, we need to understand how it's implemented and how it works.

**ACS**

- [ ] Document the integration with Google Analytics (GA4) in v2

- [ ] Validate with Marketing

**Comment by sebas-led** [comment]
According to MKT, if we integrate with GTM and add all the data layers requested, we don't need to create the integration with GA4, as they would leverage that from GTM.
Data Layers + Google Tag Manager Setup: https://docs.google.com/spreadsheets/d/1h2oiXqXCupC4v3i0cqHaLNCSWqTL79AN-I_bpjdR5TU/edit#gid=0

**Comment by codedavinci** [comment]
Easy ! LGTM
