### ISSUE TITLE
Ticketing System - Reason for creation (Operations)

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#59]
**Summary**
We will have a unified ticketing system for handling cases. Those could be started by Customers, Suppliers or even internal members. Currently, this is already happening in multiple tools and therefore, we need to understand the reason for creating a new ticket in order to have categories for each Ticket and assign a specific Squad to it. Being the highest volume generation, Operations will have a different ticket.

**ACS**

- [x] Document the reasons for creating a new ticket for Operations

- [x] Create categories based on the reason

- [ ] Validate with Ops

**Comment by Mica-pfl** [comment]
Shared with ops for review: 

https://docs.google.com/spreadsheets/d/16kbg7CNpDXGnl5m1DSiRIgxSSP0RHIhDCAgKrHVC0TA/edit#gid=868227394

**Comment by sebas-led** [comment]
LGTM

**Comment by codedavinci** [comment]
Now I understand and it looks good to me !
