### ISSUE TITLE
Ticketing System - Reason for creation (all others w/o Ops)

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#60]
**Summary**
We will have a unified ticketing system for handling cases. Those could be started by Customers, Suppliers or even internal members. Currently, this is already happening in multiple tools and therefore, we need to understand the reason for creating a new ticket in order to have categories for each Ticket and assign a specific Squad to it. This ticket involves all the other departments (TX, MKT, Accounting, Legal, Logistics)

**ACS**

- [x] Document the reasons for creating a new ticket for TX, MKT, Accounting, Legal & Logistics

- [x] Create categories based on the reason

- [x] Validate with TX, MKT, Accounting, Legal & Logistics

**Comment by sebas-led** [comment]
Waiting confirmation from Accounting to move to review: https://docs.google.com/document/d/1pPP7JjzLg3blKQRcfKLJoTOwpLQAJrjGkrGInKTCptI/edit#heading=h.cilfri8hgzks

**Comment by sebas-led** [comment]
Accounting requested until Wed Nov 2nd

**Comment by sebas-led** [comment]
https://docs.google.com/document/d/1pPP7JjzLg3blKQRcfKLJoTOwpLQAJrjGkrGInKTCptI/edit?pli=1#

**Comment by sebas-led** [comment]
New version: https://docs.google.com/spreadsheets/d/1ax26HsoUdVD-1B07ygDBq__WXDJer9nJxJJudQmYeuI/edit#gid=0

**Comment by Mica-pfl** [comment]
LGTM

**Comment by codedavinci** [comment]
LGTM
