### ISSUE TITLE
Quick Filters - Listings & LVT search results

### ISSUE THREAD

**Issue by Mica-pfl** [toursbylocals/wiki#61]
**Summary**

We offer quick filters on listings and LVTs search results, we need to define which quick filters we will show on each page. 

**ACS**

- [x] Define and document quick filters
- [x] Review & Approve by Marketing

**Comment by sebas-led** [comment]
https://docs.google.com/document/d/1gZWGSPiGDm5qFQSl-BI0EjzCQ-g0e_oX9jjLq2JuhkE/edit#
Asking MKT to review

**Comment by codedavinci** [comment]
Will there be a quick filter called "unfiltered"? @sebas-led

**Comment by sebas-led** [comment]
@codedavinci What would be the state for 'unfiltered'? Showing all listings? I haven't seen this option as a quick filter so far but curious about it...

**Comment by codedavinci** [comment]
LGTM
