### ISSUE TITLE
Document Availability & working hours in V3

### ISSUE THREAD

**Issue by Mica-pfl** [toursbylocals/wiki#62]
**Summary**

Moving forward suppliers will only have to set their working hours on their listings and set any unavailable personal time as events in their calendars. Every booking will show as a new event in their calendars blocking that time for future bookings. We need to document the business logic and flow for this change and validate it with Tourex and Operations. 

**ACS**

- [x] Document availability business logics and flow in V2
- [x] Document availability business logics and flow in V3
- [ ] Review & Approve by Tx
- [ ] Review & Approve by Ops

**Comment by Mica-pfl** [comment]
https://docs.google.com/document/d/1Mq7CaegKP07Cq3T8zZke2SCJuXG4z53Kn8EmRM7MiCc/edit?disco=AAAAjTJ_UHU

**Comment by sebas-led** [comment]
@Mica-pfl @codedavinci Only a minor note here, but what about the minimum short notice? That exists in v2 and we talked about it for v3 too. On excalidraw is called 'BookingInAdvance'

**Comment by codedavinci** [comment]
LGTM, and the field is that one @sebas-led
