### ISSUE TITLE
Tour Editor Creation: Start from a Product Selection

### ISSUE THREAD

**Issue by Mica-pfl** [toursbylocals/wiki#63]
**Summary**

Moving forward we will have different tour editor flows for each product being created by Guides (Tours, Live Virtual Tours, Safaris. etc). We need to document all business rules for each product creation. 

**ACS**
- [x] Document requirements for each product's creation 
- [ ] Review & Approve by Tourex

**Comment by Mica-pfl** [comment]
https://docs.google.com/document/d/11twdjcThmf_33WjLS70bT9ZCbYRvZyJ1ALeE7dsvrlg/edit#

**Comment by Mica-pfl** [comment]
Shared with Tx

**Comment by codedavinci** [comment]
What's the outcome of safari ?

**Comment by sebas-led** [comment]
Listings created as Safaris would show in the Safari Search Results

**Comment by codedavinci** [comment]
LGTM
