### ISSUE TITLE
Document Travel Agent profile - Requirements & Business Rules

### ISSUE THREAD

**Issue by Mica-pfl** [toursbylocals/wiki#64]
**Summary**

Travel Agents have specific account management requirements (eg having a list of customers, sharing traveller profiles with Guides, assigning bookings to travellers, etc). Document all requirements and business rules for this type of user. 

**ACS**
- [x] Document requirements & business rules
- [x] Review & Approve by Ops
- [x] Review w/ Marketing

**Comment by sebas-led** [comment]
https://docs.google.com/document/d/1NQthirS2FfmykUyloz4UFAdi6YAYeXuF2HOkRn3Mjow/edit#
Asking Ops (Hedieh) to review and approve

**Comment by Mica-pfl** [comment]
LGTM Just confirming that the TAs would have to request changes on bookings on behalf of travelers at this stage right?

**Comment by sebas-led** [comment]
Yes, that would be the case as Contacts won't login, they just get echo emails for the actions needed
