### ISSUE TITLE
Document Traveler profile - Requirements & Business Rules 

### ISSUE THREAD

**Issue by Mica-pfl** [toursbylocals/wiki#66]
**Summary**

All personal customer information will be stored in their profiles. Travellers will have the option of adding medical conditions, picture upload, etc. We need to document all information available on travellers profiles and business rules on sharing this information with Suppliers moving forward. 

**ACS**

- [x] Document requirements & business rules
- [x] Review & approve by Ops

**Comment by sebas-led** [comment]
https://docs.google.com/document/d/1vcc-Kl5WACmQ1CKAQvX9IUB6DncSfXzHwFPacjTc0tI/edit#
Shared with Ops & Augusto to approve (Geneva approved already but asked for Hedieh, Gavin & Paul H to approve too)

**Comment by sebas-led** [comment]
https://docs.google.com/document/d/1vcc-Kl5WACmQ1CKAQvX9IUB6DncSfXzHwFPacjTc0tI/edit#

**Comment by Mica-pfl** [comment]
LGTM

**Comment by codedavinci** [comment]
LGTM
