### ISSUE TITLE
SPIKE - Account Entry Types review

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#67]
**Summary**
In v2, there are 11 account entries being used for different purposes like a sale, adjustment, pay out, transaction fee, etc. Since v3 has a different architecture and types, we mainly need to ensure that the use cases are covered in any given way. As an example, Gift Card won't exist in v3.0 to be purchased and existing ones will have an option to be redeem in the wallet of the user. We could have the account entry done already for when we add Gift Card in v3.1 or left for the future, but we need to document it accordingly so the stakeholder are aware of what are the capabilities.

All Account Entries in v2: https://docs.google.com/spreadsheets/d/1juUi9mC7xSdNXSbBVdfYTBR1FislLO7sNhq0lOM69Vs/edit#gid=0

**ACS**

- [ ] Add comments on how it would work in v3 for each account entry

_Note: If changes to the back end are needed, we will create separate tickets since it's hard to estimate without knowing the scope._

**Comment by DongJoSuh** [comment]
https://docs.google.com/spreadsheets/d/1v4QtAjw_uDuThbG90hEIl56Jl4Oq-SE76yFEhsiYijc/edit#gid=0

**Comment by codedavinci** [comment]
LGTM
