### ISSUE TITLE
Document Travel Agents Reports/Metrics

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#68]
**Summary**
On the Travel Agent account, there would be a section where the reports/metrics would be shown to the users. Since this doesn't exist in v2, we would need to document which ones we would show in an initial launch.

**ACS**

- [x] Determine the metrics to show under Reports for Travel Agents

- [x] Validate with Ops

**Comment by sebas-led** [comment]
https://docs.google.com/spreadsheets/d/1QtfDfP1HB4z3-SatACJ-lFmVImhNhIMzoDMfdM6pdHQ/edit#gid=0

**Comment by Mica-pfl** [comment]
@sebas-led LGTM, should we have anything on Promo Codes for Any Reason CXL here as well?

**Comment by sebas-led** [comment]
@Mica-pfl I don't think we need that under Reports, it should show on the Pay In/Wallet section

**Comment by codedavinci** [comment]
LGTM
