### ISSUE TITLE
Document structure for Travel Agents

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#70]
**Summary**
Travel Agents get a 5% commission on every purchase done. However, after a threshold, they are considered Elite and the commission is increased to 10% with certain business rules.

**ACS**

- [x] Document the different user types

- [x] Document thresholds on each currency to be considered Elite

- [x] Document business rules when a travel agent reaches Elite Status

**Comment by sebas-led** [comment]
https://docs.google.com/document/d/1qD2SqiUN2CF_mpzUwklQPaOiCf9rfHitnL_z_h2PoHY/edit#

**Comment by Mica-pfl** [comment]
LGTM

**Comment by codedavinci** [comment]
LGTM
