### ISSUE TITLE
WIKI - Login Token

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#71]
**Summary**
We have decided to create a token and refresh it for users of different squads. However, it has not being documented in order to share with stakeholders, if needed.

**ACS**

- [x] Document login token for Customers, Suppliers, Travel Agents & Staff

**Comment by sebas-led** [comment]
https://docs.google.com/document/d/17yL-9d2WHZwxdKzhHZPPno2y915_spERgpT0te8_b2A/edit#heading=h.71iy3ru0vpox

**Comment by Mica-pfl** [comment]
LGTM
