### ISSUE TITLE
WIKI - Itineraries

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#72]
**Summary**
We will launch v3.0 with itineraries as open text, migrating the same input as on v2 for parity. In addition, we will add on the Tour Editor, the ability to incorporate POIs and at some point, launch it on the marketplace.

**ACS**

- [x] Document how the itineraries will work on v3.0

**Comment by sebas-led** [comment]
https://docs.google.com/document/d/1RtJxnfXX_XXcD9DdOHZi2AuL52UcZOecPkG9-kQUPjc/edit#

**Comment by Mica-pfl** [comment]
LGTM
