### ISSUE TITLE
WIKI - Meeting Location

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#73]
**Summary**
We offer up to 8 meeting location options at checkout to customers in v2. It was determined that we will offer only 3 options in v3, but was never documented. In order to prevent further challenges with the field, we will create a documentation for this change.

**ACS**

- [x] How Meeting Location works in v2 and how it will work in v3

**Comment by sebas-led** [comment]
https://docs.google.com/document/d/1NZ7dJ0zlMvtS57Tzucc1oIlICQEFCUZ1Sxcqo93ZtbM/edit#

**Comment by Mica-pfl** [comment]
LGTM
