### ISSUE TITLE
WIKI - Editable fields for Suppliers & Listings

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#74]
**Summary**
We need to determine which fields a supplier will be able to edit and which ones won't when it comes to their own profile and listings.

**ACS**

- [x] Editable fields for Supplier Profile

- [x] Editable fields for Listings

**Comment by sebas-led** [comment]
https://docs.google.com/spreadsheets/d/10GCK__DUx1Ni-q-WH0-LbWSMKEv_5BgrcXfyzbMS1y0/edit#gid=0

**Comment by codedavinci** [comment]
LGTM
