### ISSUE TITLE
SPIKE - User Verification attributes

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#75]
**Summary**
Using Adyen as a provider for Payments, guides will need to be verified in order to allow pay outs. In addition, guides will also run through an ID verification to join the platform, during the onboarding process. We need to determine which attributes are required to be verified by Adyen in order to consider them. Depending on the outcome, some prototypes and back end collections may need to be updated to include the necessary fields.

**ACS**

- [x] Fields Required to Verify an individual

- [x] Fields Required to Verify an organization

- [x] Fields Required to Verify a sole proprietorship

**Comment by sebas-led** [comment]
https://docs.google.com/document/d/1M4G-I_sMJ78wb4Q58KNzmgNwWx7KWJ5_DyYNvpH0f00/edit#heading=h.125l70csy8z1

**Comment by codedavinci** [comment]
LGTM
