### ISSUE TITLE
SPIKE - Travel Agent Account

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#77]
**Summary**
ToursByLocals operates with different partners such as Travel Agencies, Travel Agents and Affiliates. There has always been a question on how other competitors work with them and what tools are useful for this type of user. In order to create an updated approach for the Travel Agent account and how they apply to become a partner, a research is needed to better understand the structures and common practices.

**ACS**
- [x] Research on how Get Your Guide, Viator & Expedia work with Affiliates such as Travel Agents to answer the following questions:

- How the Travel Agents apply and get full access to their accounts
- What's the account options and setup
- What's the booking process and commission attribution options
- What's the traveler information required to make a booking

**Comment by codedavinci** [comment]
LGTM
