### ISSUE TITLE
Account Navigation - Travel Agents

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#78]
**Summary**
Based on the SPIKE done on https://github.com/toursbylocals/wiki/issues/77 we need to determine the Account navigation for Travel Agents and how they make a booking in order to be attributed for the commission.

**ACS**

- [x] Describe each account section, navigation and it's content

- [x] Describe the booking process for Travel Agents

**Comment by sebas-led** [comment]
https://docs.google.com/document/d/1qUI08UDqNs16LOpXQIggpeFhgZtxQoPOPp6QKlBp3ho/edit#

**Comment by Mica-pfl** [comment]
LGTM

**Comment by codedavinci** [comment]
LGTM
