### ISSUE TITLE
WIKI - Change Booking Process

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#79]
**Summary**
On v2, Guides can edit the Meeting Location without the need for any confirmation from Traveler. On the other hand, Travelers need to request to Support if they wish to make any changes to their bookings. As part of the efficiencies, we have determined that for v3, both Guides and Travelers will have the ability to request a change to Meeting location, Tour Date and Start Time and the other party will need to accept/reject the change.

**ACS**

- [x] Document the Change Booking process in v2

- [x] Document the Change Booking process in v3

- [x] Approved by Operations

**Comment by sebas-led** [comment]
https://docs.google.com/document/d/1qiUqJpNxxUGlm-e-R-5mxeAsUm7r-AMcuIYa8HIDoDc/edit#

**Comment by sebas-led** [comment]
Documented the Change booking process that is already in place, with the differences with how it works on v2. Meeting Location, Start Time and Tour Date are editable by Guide/Traveler/Travel Agent and need to be confirmed by the other party to take place. All the change requests/confirmations are recorded in the booking history

**Comment by Mica-pfl** [comment]
LGTM

**Comment by martyhurl** [comment]
Can both parties request to have the same attribute changed at the same time, or is only 1 change request allowed? Ie, I am a traveler and I have a booking with a guide. I request a change to the meeting location. The guide does not action this request for whatever reason. Is it possible that the guide can also now go into the booking and edit the meeting location and send a request to the traveler?

**Comment by martyhurl** [comment]
Is there a cut-off point for change requests to confirmed bookings? Ie, can requests be made up until tour start time or should change requests be disabled say 24 hours out?

**Comment by martyhurl** [comment]
Which booking statuses allow booking change requests ?

**Comment by martyhurl** [comment]
Do we need to define a business rule to not allow a request of a date in the past?

**Comment by Mica-pfl** [comment]
- Guide would have to responde to the change request before suggesting a change for the same attribute
- I'll check in with ops to know on average how long it takes them to transfer a booking to another Guide and let you know what would make more sense
- Change requests are only applicable to confirmed bookings 
- Dates in the past meaning before the booking? If they want to push the booking forward that's ok

Good questions @martyhurl thank you, will keep you posted and add these business rules to the doc if you agree with the above @sebas-led

**Comment by martyhurl** [comment]
@Mica-pfl  date in the past as in a date that has been and gone, ie , they shouldn't be able to request a tour date change who requested new tour date is before today

**Comment by Mica-pfl** [comment]
> @Mica-pfl date in the past as in a date that has been and gone, ie , they shouldn't be able to request a tour date change who requested new tour date is before today

in that case yes, we need that business rule

**Comment by DongJoSuh** [comment]
Are we going to have a separate business rules documentation for `edit tour price`? It is part of `edit tour` and has various rule itself.

**Comment by sebas-led** [comment]
@DongJoSuh `edit tour price` details added now in the same document. On v2, there are several rules, which were simplified for v3. Business rules around how many times a booking can have the price edited if there is a per person price component is no longer needed.

**Comment by Mica-pfl** [comment]
LGTM

**Comment by codedavinci** [comment]
## OUTCOME

For now we decided to fully focus on marketplace, we'll revisit it once we start building it.

**Comment by sebas-led** [comment]
@Mica-pfl @nk18chi Could you review this? It's documentation about the process and business rules for editing a booking and impacts the Back End. Thanks !

**Comment by Mica-pfl** [comment]
LGTM

**Comment by DongJoSuh** [comment]
> 

This is the 'adjustment' in v2 that we talked about before. It does happen often i believe.

**Comment by sebas-led** [comment]
@nk18chi As Joe mentioned, it's a process that happens frequently, but in general more on a price increase than a decrease. Cancellation Policy is not refundable so we don't need any solution for that. However, the 'adjustments' would need to trigger the refund/recharge

**Comment by nk18chi** [comment]
Thank you for the clarification. LGTM 👍
