### ISSUE TITLE
WIKI - Medical Concerns and Dietary restrictions

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#80]
**Summary**
On v2, Medical Concerns and Dietary restrictions are added by each user during the checkout process, with ability to share their own and also anyone in their party. However, on v3 this information is not part of the checkout process but rather part of the Traveler Profile in order to reduce the steps in the checkout process and to make it more streamline on where to add each piece of information.

**ACS**

- [x] Document the process to add Medical Concerns and Dietary restrictions in v2

- [x] Document the process to add Medical Concerns and Dietary restrictions in v3

- [x] Approved by Operations

**Comment by sebas-led** [comment]
https://docs.google.com/document/d/1XH7giCR6nAhQoXAaBZ4joK7Ch7uEgF7MT9My-MscXlo/edit#

**Comment by sebas-led** [comment]
Documented the two states in v2 and the single state in v3 as group members' will be shared via messaging system.
Added where CRUD would happened and where it would be used

**Comment by martyhurl** [comment]
👍

**Comment by Mica-pfl** [comment]
LGTM
