### ISSUE TITLE
WIKI - Interaction Quality Control Process (suspended messages)

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#81]
**Summary**
It was determined that in v3, we won't be suspended every message that contains trivial words but rather a combination of flagging messages with blocking specific trigger words. We have documented which ones would go on either direction but never the actual process of how it would work.

**ACS**

- [x] Document the Suspended Messages Process in v2

- [x] Document the Interaction Quality Control in v3

- [x] Approved by Operations

**Comment by sebas-led** [comment]
https://docs.google.com/document/d/1ZQNiFH0cs00CClX4uQWmCWoKQdY8s2H8dNyC4s-Ni5k/edit#heading=h.wp3yfq0erij

**Comment by sebas-led** [comment]
Document reviewed by Paul H and Alex G from Operations. The doc contains the different levels/categories, the template for the notification via ticketing system and the Interaction Quality Control Module in the Dashboard for Admins

**Comment by Mica-pfl** [comment]
LGTM

**Comment by martyhurl** [comment]
We will possibly need some architect some back end for the whitelisted Urls

**Comment by martyhurl** [comment]
I believe currently in v2, all attachments sent are flagged for admins to review in the suspended message centre (there may be some exception for if there is a confirmed booking, I'm not sure). Same case for v3?

**Comment by martyhurl** [comment]
👍

**Comment by codedavinci** [comment]
## OUTCOME. 

We decided to move it back to backlog because this work is not the focus of this sprint.

**Comment by sebas-led** [comment]
@Mica-pfl @nk18chi Could you review this? It's documentation about the process and business rules for Interaction Quality Control, which is the Admin Tool to choose trigger words that would be blocked in the `Messaging System` (we chat about it on last pre-grooming but would be good to get your review for the back end). Thanks !

**Comment by Mica-pfl** [comment]
LGTM

**Comment by nk18chi** [comment]
LGTM
