### ISSUE TITLE
WIKI - Checkout Process

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#82]
**Summary**
The checkout process in v2 involves between 5-8 steps with different flows depending if it's a single booking, a Live Virtual Tour and/or the Shopping Cart. However, for v3 we are having 2 steps in a single flow without the shopping cart. 

**ACS**

- [x] Document the checkout process in v2

- [x] Document the checkout process in v3

- [x] Document where are the missing steps in v3 along the customer journey

- [x] Document what we are not carrying over for v3 when it comes to the checkout process

- [ ] Share with Operations & Marketing (it has been approved by Paul & Dave, so only sharing)

**Comment by sebas-led** [comment]
https://docs.google.com/document/d/1KgXQl65l1Xuh3POoH1vaUqwm68IcYiphcvQ7JqSFLvA/edit#heading=h.ft4yc67m2xi5

**Comment by sebas-led** [comment]
Had to document the 3 flows for v2 and the differences between Traveler & Agent flows. Included the business rules for devs and the differences between Traveler & Agent checkout (contact and payment method selection that were discussed recently)

**Comment by Mica-pfl** [comment]
LGTM

**Comment by martyhurl** [comment]
Currently we allow multiple promo codes to be used on a single booking, will this be the case for v3? Otherwise 👍

**Comment by sebas-led** [comment]
Thanks @martyhurl ! Both questions were now added to the document:
> Do we allow multiple promo codes to be used on a single booking?

Yes, same as on v2

> What happens if a transaction is declined from the payment processor?

Great question. I do think that the user should be presented again with the Booking Breakdown to change the Payment Method selected from their Wallet. @codedavinci , would you have any concerns from the technical side?

**Comment by growebux** [comment]
What are we going to show when an invalid coupon code is inserted into the coupon field, what are the states of a possible invalid coupon code and how the user can track which coupon code is expired?

**Comment by sebas-led** [comment]
@growebux As for the promo codes, amounts, expiration and so on, they can find them in the wallet.
<img width="633" alt="Screen Shot 2023-02-13 at 11 38 52 AM" src="https://user-images.githubusercontent.com/107880609/218487520-16c93d8d-0b31-472d-a7f2-50ee065419c5.png">

Business rules added to the document for each state of the coupon being redeemed:

- If the Promo Code doesn’t exist in the Database, show ‘This promotional code does not match a code issued by our system. Please check your typing and try again.’
- If the Promo Code is expired, show ‘This promotional code has expired.’
- If the Promo Code has restrictions that doesn’t allow it to be applied, show ‘This promotional code is restricted. Please, contact Support for more details’
- If the Promo Code is valid, apply the discount to the total price to be paid

**Comment by growebux** [comment]
@sebas-led @ecurtosi99 @Mica-pfl 

Thanks, Sebas! As I see the indicator describes an action or alert, for that I need to apply them to the UI.

Another question is, is there any other alert the user will receive after submitting a promo code instead of "Success" or " Promo Code Invalid"?

![Screenshot 2023-02-21 at 11 12 55 AM](https://user-images.githubusercontent.com/70495348/220437428-d3bbb3f8-7800-499d-a871-f9ea384d3528.png)

**Comment by sebas-led** [comment]
@growebux No, those are the options

**Comment by growebux** [comment]
@sebas-led Thanks

**Comment by codedavinci** [comment]
What's the outcome of this ?

**Comment by sebas-led** [comment]
**Outcome**
v2: 3 check out processes (single, cart and live virtual tour) with 5-8 steps each
v3: Single check out process with 2 steps (details & breakdown) for Customers and 3 steps (contact selection, details and breakdown for Agents
Included business rules for Promo Code validation as well (error options)

**Comment by codedavinci** [comment]
## OUTCOME

Due to the focus of our team, we decided to cross this bridge once we get there.
