### ISSUE TITLE
Adyen Integration | Chargebacks

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#93]
**Background**
We capture and split the funds on Adyen after Guide Accepts the booking. If a Customer process a Chargeback, we need to instruct Adyen how to proceed with the funds and from which balance account it would come from.

Business Rule:

- If a Chargeback is requested by Customer, use the same split as on capture for that booking. 
- It should have the ability to overwrite it on Adyen if needed based on the specific case.

**ACS**

- [ ] Create automatic split on Adyen when a Chargeback is requested, following the business rules
- [ ] Create an ability to overwrite the automatic business rule on Adyen portal, if needed

**Comment by nk18chi** [comment]
### Q&A

- Could you provide an example of "the specific case"?
For example, a customer is dissatisfied with the tour they received, but the supplier has already paid certain expenses such as tickets, rental cars, or fuel costs.

- Who has the ability to change the amount of chargebacks?
Only TBL has the ability to change the amount of chargebacks, not the supplier. 

- Does the chargeback process require approval from TBL?
Yes. If a chargeback request is received, TBL will contact the supplier to verify if it is fair to refund the customer. In special cases like the one mentioned above, the refund amount may be adjusted.

- It appears that the ability to override the automatic business rule is part of Kitchen. Do you think we should address this later?
It is possible. We will use this API for Kitchen, and we already have a clear understanding of the current implementation plan. It might be beneficial to proceed with implementing this functionality at present. Let's discuss it during the grooming session.

- Who will pay the transfer fee?
TBL will cover the transfer fee.

**Comment by growebux** [comment]
Q&A
--

- How will the system detect and process the chargeback request initiated by the customer?

- What mechanism will be in place to trigger the automatic split on Adyen once a chargeback is requested?
