### ISSUE TITLE
SPIKE - HSBC & PayPal Integration Processes

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#94]
**Background**
About 50% of our Suppliers & 20% of our transactions are not covered by Adyen. In those cases, we need to get the funds from Adyen transferred into ToursByLocals HSBC account and process the payouts from HSBC. Since the business also wants to keep PayPal as a payout option (about 60% Suppliers are paid via PayPal on v2), we also need to send funds from HSBC to PayPal to proceed with the payout to Suppliers.

**ACS**

- [x] Analyze v2 setup for HSBC and PayPal

- [x] Map out all the processes related to how it will distinguish if a booking needs to be paid via Adyen, HSBC or PayPal

- [ ] Map out all the processes and flows required to transfer funds using HSBC and PayPal

- [x] Create an excalidraw flowchart for the three options: Adyen, HSBC and PayPal

- [ ] Update our wiki

**Useful Resources**
Payout tools, processes and business rules on v2 for PayPal & HSBC: https://docs.google.com/document/d/1z5za9Sv4CUTvzH6fpIgdljRirGvteCtKy8JJP74ww1U/edit#
Money Flow: https://drive.google.com/file/d/1gJkUvzqcdI3KTOGSRFMtq8DE27pT20_1/view
PayPal developer portal: https://developer.paypal.com/docs/payouts/

**Comment by martyhurl** [comment]
@sebas-led @Mica-pfl Can we please get links to the correct documentation needed for these integrations in v3 please

**Comment by Mica-pfl** [comment]
Hey @martyhurl,  @sebas-led is working on more detailed documentation on current hsbc set up, money flow is out for approval but you can take a look here: 

https://drive.google.com/file/d/1gJkUvzqcdI3KTOGSRFMtq8DE27pT20_1/view

**Comment by sebas-led** [comment]
@martyhurl All docs added to the ticket as Useful Resources now

**Comment by martyhurl** [comment]
@sebas-led @Mica-pfl  Sorry still confused as to what HSBC docs/api's we should be using ? They have many!

**Comment by sebas-led** [comment]
> Is there some other applciation you could use to export this, how do i open .drawio? Can you make on excalidraw or export as a PDF that is zoomable without losing the details?

Top center, it says 'Open with diagrams.net'. If you click there, it will ask you to install a plug in and open it in the native app where you can zoom in/out and so on.

**Comment by sebas-led** [comment]
> Sorry still confused as to what HSBC docs/api's we should be using ? They have many!

It will be the same integration as on v2, whoever takes this ticket can check for any details with Dave about HSBC

**Comment by nk18chi** [comment]
@DongJoSuh 
Thank you, Joe! According to the docs, we only require the email address as the destination to transfer money. Do you think it's necessary for us to verify if an account has been created with that email and if the account was created by the guide in PayPal(authentication)? Perhaps, during the onboarding process, we should consider checking the account verification using this API (I don't have much knowledge about PayPal, so please let me know if you know any better APIs). 
https://developer.paypal.com/docs/api/identity/v1/#userinfo_get

**Comment by sebas-led** [comment]
We had Product Steering yesterday and, based on the information we already got (thank you @DongJoSuh for that!), we decided to consume the service as it's on v2. Eddie will work on the actual implementation with Dave and we will keep the SFTP service we have on v2

**Comment by DongJoSuh** [comment]
> @DongJoSuh Thank you, Joe! According to the docs, we require the email address as the destination to transfer money. Do you think it's necessary for us to verify if an account has been created with that email and if the account was created by the guide in PayPal(authentication)? Perhaps, during the onboarding process, we should consider checking the account verification using this API (I don't have much knowledge about PayPal, so please let me know if you know any better APIs). https://developer.paypal.com/docs/api/identity/v1/#userinfo_get

as we discussed, paypal requires openIDconnect to get user information and its out of scope. For now we can just get the user paypal email address.

**Comment by Mica-pfl** [comment]
@DongJoSuh Thank you Joe! According to ticket https://github.com/toursbylocals/tblv3/issues/556 the PayPal pay out flow be slightly different to the one on your diagram. Could you adjust it accordingly?

**Comment by DongJoSuh** [comment]
> @DongJoSuh Thank you Joe! According to ticket [toursbylocals/tblv3#556](https://github.com/toursbylocals/tblv3/issues/556) the PayPal pay out flow be slightly different to the one on your diagram. Could you adjust it accordingly?

Thanks Mica, I have updated the flowchart accordingly :)

**Comment by Mica-pfl** [comment]
LGTM

**Comment by codedavinci** [comment]
## OUTCOMES
- We are going to create an integration with `Paypal` api for payouts, so whenever the `suppliers` request to be paid through it, it will trigger the  `transfer` with `Paypal`
- As for `HSBC` we decided to leverage the `V2` service, wrap it in a `Java` API so it can be integrated in the `v3`  backend (`tblv3-api` / `webhooks`)


## CONCLUSIONS
- Paypal will behave as a financial bucket for `suppliers` who request to be paid via it. 
- Accounting team will be responsible to top-up the `TBLPayPalAccount`
- There will be no split when it comes to `suppliers` who decide to be paid via `Paypal`, because there'll always have money in the `Paypal` financial bucket, **however, when the `supplier` withdraw the money from `Paypal`, an automatic service will send the same amount from `HSBC` to `Paypal` to make sure it tops-up**

ex:
```
// Supplier delivered a tour of 1000 USD
// Supplier must get 750 USD
// Supplier opted to be paid via Paypal
// Supplier requests to be paid

// Booking has been completed ? 
//if Yes, Paypal Service Issues Payment  -> 750USD
// HSBC issues top-up of 750USD -> Paypal 

```
### **PS: This rudimentary example is not showcasing any type of FX or Taxes being applied upon the commission or chargebacks , simply the flow of transfers.**

**Comment by codedavinci** [comment]
## FEEDBACK 

I have validated the conclusions and based on the comment above, it LGTM
